export const strings = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    planner: 'Fertilizer Planner',
    weather: 'Weather',
    calendar: 'Crop Calendar',
    dashboard: 'Dashboard',
    history: 'History',
    logout: 'Logout',
    tutorials: 'Tutorials',
    
    // Login
    login: 'Login',
    email: 'Email',
    password: 'Password',
    loginButton: 'Login',
    loginError: 'Invalid credentials',
    loginSuccess: 'Login successful',
    
    // Home
    welcome: 'Welcome to Fertilizer Recommendation System',
    description: 'Get AI-powered fertilizer recommendations for your crops',
    
    // Planner
    fertilizerPlanner: 'Fertilizer Recommendation Planner',
    n: 'Nitrogen (N)',
    p: 'Phosphorus (P)',
    k: 'Potassium (K)',
    temperature: 'Temperature (°C)',
    humidity: 'Humidity (%)',
    ph: 'pH Level',
    moisture: 'Moisture (%)',
    crop: 'Crop Type',
    getRecommendation: 'Get Recommendation',
    recommendation: 'Recommendation',
    fertilizer: 'Fertilizer',
    dosage: 'Dosage',
    remarks: 'Remarks',
    downloadPDF: 'Download PDF',
    selectCrop: 'Select Crop',
    soilType: 'Soil Type',
    hectareArea: 'Hectare Area',
    selectSoilType: 'Select Soil Type',
    primaryRecommendation: 'Primary Recommendation',
    alternativeOptions: 'Alternative Options',
    alternativeSubtitle: 'Instead of the primary recommendation, you can also consider these alternatives:',
    alternative: 'Alternative',
    additionalSuggestions: 'Additional Suggestions & Tips',
    
    // Dashboard
    modelAccuracy: 'Model Accuracy',
    accuracy: 'Accuracy',
    precision: 'Precision',
    recall: 'Recall',
    f1Score: 'F1-Score',
    
    // History
    recommendationHistory: 'Recommendation History',
    timestamp: 'Timestamp',
    inputs: 'Inputs',
    noHistory: 'No recommendation history found',
    searchHistory: 'Search by crop, fertilizer, or soil type...',
    sortBy: 'Sort By',
    newestFirst: 'Newest First',
    oldestFirst: 'Oldest First',
    showing: 'Showing',
    of: 'of',
    recommendations: 'recommendations',
    noResults: 'No results found',
    
    // About
    aboutTitle: 'About This System',
    aboutContent: 'This system uses Machine Learning (Decision Tree Classifier) to recommend the best fertilizer for your crops based on soil conditions and environmental factors.',
    
    // Weather
    weatherInfo: 'Weather Information',
    weatherPlaceholder: 'Enter a location to get weather information',
    location: 'Location',
    enterLocation: 'Enter city or region name',
    selectDistrict: 'Select District',
    getWeather: 'Get Weather',
    loading: 'Loading...',
    windSpeed: 'Wind Speed',
    rainfall: 'Rainfall',
    forecast: '3-Day Forecast',
    farmingTips: 'Farming Tips',
    highTempTip: 'High temperature detected. Ensure adequate irrigation and shade for crops.',
    rainfallTip: 'Rainfall expected. Avoid fertilizer application during heavy rain.',
    highHumidityTip: 'High humidity may increase disease risk. Monitor crops closely.',
    idealConditionsTip: 'Ideal weather conditions for farming activities.',
    
    // Crop Calendar
    cropCalendar: 'Crop Calendar & Seasonal Guide',
    calendarSubtitle: 'Know when to plant, when to harvest, and how to protect your crops from weather',
    selectSeason: 'Select Growing Season',
    kharif: 'Kharif (Monsoon)',
    rabi: 'Rabi (Winter)',
    zaid: 'Zaid (Summer)',
    kharifMonths: 'June - October',
    rabiMonths: 'November - March',
    zaidMonths: 'March - June',
    cropsForSeason: 'Crops for',
    plantingTime: 'Planting Time',
    harvestTime: 'Harvest Time',
    duration: 'Crop Duration',
    viewDetails: 'View Details',
    details: 'Details',
    rainfallRequirements: 'Rainfall Requirements',
    idealRainfall: 'Ideal Rainfall',
    harmfulRainfall: 'Harmful Rainfall Conditions',
    protectionMeasures: 'Protection Measures',
    cultivationTips: 'Cultivation Tips',
    checkRainfallImpact: 'Check Rainfall Impact',
    enterRainfall: 'Enter expected rainfall',
    protection: 'Protection',
    excessiveRainfall: '⚠️ Excessive Rainfall Warning',
    insufficientRainfall: '⚠️ Insufficient Rainfall Warning',
    needIrrigation: 'Irrigation required. Ensure adequate water supply.',
    generalTips: 'General Agricultural Tips',
    rainfallManagement: 'Rainfall Management',
    temperatureControl: 'Temperature Control',
    cropRotation: 'Crop Rotation',
    irrigationTiming: 'Irrigation Timing',
    rainfallManagementTip: 'Monitor rainfall patterns. Excess rain can cause waterlogging and disease. Ensure proper drainage.',
    temperatureTip: 'Extreme temperatures can stress crops. Use shade nets, mulching, or adjust planting times.',
    rotationTip: 'Rotate crops to maintain soil fertility, reduce pests, and prevent nutrient depletion.',
    irrigationTip: 'Water crops early morning or evening. Avoid midday irrigation to prevent water loss through evaporation.',
    
    // Month names
    juneJuly: 'June - July',
    sepOct: 'September - October',
    mayJune: 'May - June',
    octDec: 'October - December',
    decJan: 'December - January',
    novDec: 'November - December',
    aprMay: 'April - May',
    janFeb: 'January - February',
    mayJun: 'May - June',
    mayJul: 'May - July',
    octNov: 'October - November',
    febMar: 'February - March',
    marApr: 'March - April',
    
    // Crop-specific rainfall warnings
    riceHarmfulRain: 'Heavy rainfall during flowering (40-50 days after planting) can damage panicles. Waterlogging for more than 3 days can kill plants.',
    riceProtection: 'Maintain proper drainage. Use raised beds. Harvest early if heavy rain is forecasted during maturity.',
    riceTip1: 'Transplant seedlings 20-25 days after sowing in nursery',
    riceTip2: 'Maintain 5-7 cm water depth during vegetative stage',
    riceTip3: 'Apply nitrogen in split doses: 50% basal, 25% at tillering, 25% at panicle initiation',
    
    wheatHarmfulRain: 'Rainfall during grain filling and maturity can cause lodging, sprouting, and fungal diseases like rust and blight.',
    wheatProtection: 'Harvest before heavy rains. Use disease-resistant varieties. Apply fungicides if rain persists during heading.',
    wheatTip1: 'Sow at proper time (mid-November to early December) for best yield',
    wheatTip2: 'Apply first irrigation at crown root initiation (20-25 days after sowing)',
    wheatTip3: 'Control weeds with pre-emergence herbicides',
    
    tomatoHarmfulRain: 'Heavy rain can cause fruit cracking, blossom drop, and increase risk of blight, bacterial spot, and fruit rot diseases.',
    tomatoProtection: 'Use raised beds with good drainage. Cover plants during heavy rain. Apply fungicides preventively.',
    tomatoTip1: 'Stake or cage plants for better support and air circulation',
    tomatoTip2: 'Mulch around plants to prevent soil splash and maintain moisture',
    tomatoTip3: 'Water at base, avoid overhead irrigation to prevent disease',
    
    cottonHarmfulRain: 'Excessive rain during boll formation can cause boll rot, shedding, and reduce fiber quality. Waterlogging damages roots.',
    cottonProtection: 'Ensure proper drainage. Use ridge and furrow system. Harvest open bolls before heavy rain.',
    cottonTip1: 'Plant at recommended spacing (60-90 cm between rows)',
    cottonTip2: 'Control weeds in first 40-50 days after planting',
    cottonTip3: 'Apply balanced NPK with emphasis on potassium for better boll development',
    
    // Additional Crop Details
    cropDetailsNotAvailable: 'Detailed information for this crop is being updated. Please check back soon.',
    
    // Maize
    maizeHarmfulRain: 'Heavy rain during flowering and grain filling can cause lodging and reduce yield. Waterlogging damages roots.',
    maizeProtection: 'Ensure proper drainage. Use ridge planting. Harvest before heavy rains during maturity.',
    maizeTip1: 'Plant at spacing of 60-75 cm between rows and 20-25 cm between plants',
    maizeTip2: 'Apply nitrogen in split doses: 50% at planting, 25% at knee-high stage, 25% at tasseling',
    maizeTip3: 'Control weeds in first 30-40 days after planting',
    
    // Sugarcane
    sugarcaneHarmfulRain: 'Excessive rain can cause waterlogging, root rot, and reduce sugar content. Flooding damages the crop.',
    sugarcaneProtection: 'Maintain proper drainage channels. Use raised beds. Avoid water stagnation.',
    sugarcaneTip1: 'Plant setts in furrows at 90-120 cm spacing',
    sugarcaneTip2: 'Apply first irrigation immediately after planting, then at 10-15 day intervals',
    sugarcaneTip3: 'Earthing up should be done 90-120 days after planting',
    
    // Groundnut
    groundnutHarmfulRain: 'Heavy rain during pod formation can cause pod rot and reduce yield. Waterlogging affects root development.',
    groundnutProtection: 'Ensure good drainage. Use raised beds. Harvest before heavy rains to prevent pod rot.',
    groundnutTip1: 'Plant seeds at 30-45 cm spacing between rows and 10-15 cm between plants',
    groundnutTip2: 'Apply gypsum at flowering stage for better pod development',
    groundnutTip3: 'Control weeds in first 30-40 days after planting',
    
    // Soybean
    soybeanHarmfulRain: 'Excessive rain during flowering and pod filling can cause lodging and pod drop. Waterlogging damages roots.',
    soybeanProtection: 'Maintain proper drainage. Use disease-resistant varieties. Harvest before heavy rains.',
    soybeanTip1: 'Plant seeds at 45-60 cm spacing between rows',
    soybeanTip2: 'Inoculate seeds with Rhizobium culture before planting',
    soybeanTip3: 'Apply phosphorus at planting for better root and pod development',
    
    // Turmeric
    turmericHarmfulRain: 'Excessive rain can cause rhizome rot and fungal diseases. Waterlogging damages the crop.',
    turmericProtection: 'Ensure excellent drainage. Use raised beds. Apply fungicides preventively during rainy season.',
    turmericTip1: 'Plant rhizomes in well-prepared beds at 30-45 cm spacing',
    turmericTip2: 'Apply organic manure and balanced NPK fertilizers',
    turmericTip3: 'Mulch the field to conserve moisture and control weeds',
    
    // Ginger
    gingerHarmfulRain: 'Heavy rain can cause rhizome rot, bacterial wilt, and reduce yield. Waterlogging is very harmful.',
    gingerProtection: 'Excellent drainage is essential. Use raised beds. Apply fungicides and bactericides preventively.',
    gingerTip1: 'Plant rhizomes in well-drained beds at 30-40 cm spacing',
    gingerTip2: 'Apply organic manure and balanced fertilizers',
    gingerTip3: 'Mulch heavily to conserve moisture and prevent soil splash',
    
    // Barley
    barleyHarmfulRain: 'Rainfall during grain filling and maturity can cause lodging and reduce grain quality.',
    barleyProtection: 'Harvest before heavy rains. Use lodging-resistant varieties. Ensure proper drainage.',
    barleyTip1: 'Sow at proper time (mid-November) for best yield',
    barleyTip2: 'Apply first irrigation at crown root initiation stage',
    barleyTip3: 'Control weeds with pre-emergence herbicides',
    
    // Mustard
    mustardHarmfulRain: 'Heavy rain during flowering and pod formation can cause pod shattering and reduce yield.',
    mustardProtection: 'Harvest before heavy rains. Use pod-shattering resistant varieties. Ensure proper drainage.',
    mustardTip1: 'Sow seeds at 30-45 cm spacing between rows',
    mustardTip2: 'Apply first irrigation at rosette stage (30-35 days after sowing)',
    mustardTip3: 'Control aphids and other pests during flowering stage',
    
    // Potato
    potatoHarmfulRain: 'Excessive rain can cause tuber rot, late blight disease, and reduce yield. Waterlogging damages tubers.',
    potatoProtection: 'Ensure excellent drainage. Use raised beds. Apply fungicides preventively. Harvest before heavy rains.',
    potatoTip1: 'Plant seed tubers at 60-75 cm spacing between rows and 20-25 cm between plants',
    potatoTip2: 'Apply first irrigation immediately after planting',
    potatoTip3: 'Earthing up should be done 30-40 days after planting',
    
    // Onion
    onionHarmfulRain: 'Heavy rain during bulb formation can cause bulb rot and reduce storage quality. Waterlogging damages roots.',
    onionProtection: 'Ensure good drainage. Use raised beds. Harvest and dry properly before storage.',
    onionTip1: 'Transplant seedlings at 15-20 cm spacing between rows and 10 cm between plants',
    onionTip2: 'Apply first irrigation immediately after transplanting',
    onionTip3: 'Stop irrigation 15-20 days before harvest for better bulb quality',
    
    // Carrot
    carrotHarmfulRain: 'Excessive rain can cause root splitting and rot. Waterlogging affects root development.',
    carrotProtection: 'Ensure good drainage. Use raised beds. Harvest before heavy rains to prevent splitting.',
    carrotTip1: 'Sow seeds in well-prepared beds at 30-45 cm spacing between rows',
    carrotTip2: 'Thin seedlings to 5-8 cm spacing when they are 5-7 cm tall',
    carrotTip3: 'Apply balanced fertilizers, avoid excess nitrogen',
    
    // Cabbage
    cabbageHarmfulRain: 'Heavy rain can cause head splitting and increase disease risk. Waterlogging damages roots.',
    cabbageProtection: 'Ensure good drainage. Use raised beds. Cover heads during heavy rain if possible.',
    cabbageTip1: 'Transplant seedlings at 45-60 cm spacing',
    cabbageTip2: 'Apply first irrigation immediately after transplanting',
    cabbageTip3: 'Ensure adequate nitrogen for leaf development',
    
    // Cauliflower
    cauliflowerHarmfulRain: 'Excessive rain can cause curd rot and reduce quality. Waterlogging damages the plant.',
    cauliflowerProtection: 'Ensure excellent drainage. Use raised beds. Cover curds during heavy rain.',
    cauliflowerTip1: 'Transplant seedlings at 45-60 cm spacing',
    cauliflowerTip2: 'Apply first irrigation immediately after transplanting',
    cauliflowerTip3: 'Tie leaves over curd to protect from sun and rain',
    
    // Cucumber
    cucumberHarmfulRain: 'Heavy rain can cause fruit rot, powdery mildew, and reduce yield. Waterlogging damages roots.',
    cucumberProtection: 'Ensure good drainage. Use raised beds. Apply fungicides preventively. Provide support for vines.',
    cucumberTip1: 'Sow seeds at 90-120 cm spacing between rows',
    cucumberTip2: 'Provide trellis or support for better growth and fruit quality',
    cucumberTip3: 'Apply balanced fertilizers, ensure adequate water during fruiting',
    
    // Watermelon
    watermelonHarmfulRain: 'Excessive rain can cause fruit splitting, rot, and reduce sugar content. Waterlogging damages roots.',
    watermelonProtection: 'Ensure excellent drainage. Use raised beds. Harvest before heavy rains. Cover fruits if possible.',
    watermelonTip1: 'Sow seeds at 150-200 cm spacing between rows',
    watermelonTip2: 'Apply first irrigation immediately after sowing',
    watermelonTip3: 'Reduce irrigation 10-15 days before harvest for better sugar content',
    
    // Pumpkin
    pumpkinHarmfulRain: 'Heavy rain can cause fruit rot and increase disease risk. Waterlogging damages the plant.',
    pumpkinProtection: 'Ensure good drainage. Use raised beds. Provide support for vines. Harvest before heavy rains.',
    pumpkinTip1: 'Sow seeds at 150-200 cm spacing between rows',
    pumpkinTip2: 'Provide support or allow to trail on ground',
    pumpkinTip3: 'Apply balanced fertilizers, ensure adequate water during fruiting',
    
    // Brinjal
    brinjalHarmfulRain: 'Excessive rain can cause fruit rot, bacterial wilt, and reduce yield. Waterlogging damages roots.',
    brinjalProtection: 'Ensure excellent drainage. Use raised beds. Apply fungicides and bactericides preventively.',
    brinjalTip1: 'Transplant seedlings at 60-75 cm spacing',
    brinjalTip2: 'Stake plants for better support and air circulation',
    brinjalTip3: 'Apply balanced fertilizers, ensure adequate water during fruiting',
    
    // Chilli
    chilliHarmfulRain: 'Heavy rain can cause fruit drop, anthracnose, and reduce yield. Waterlogging damages roots.',
    chilliProtection: 'Ensure good drainage. Use raised beds. Apply fungicides preventively. Harvest before heavy rains.',
    chilliTip1: 'Transplant seedlings at 45-60 cm spacing',
    chilliTip2: 'Stake plants for better support',
    chilliTip3: 'Apply balanced fertilizers, ensure adequate water during flowering and fruiting',
    
    // Fertilizer Names
    fertilizerNPK: 'NPK 19:19:19',
    fertilizerUrea: 'Urea',
    fertilizerDAP: 'DAP',
    fertilizerPotash: 'Potash',
    fertilizerCompost: 'Compost',
    fertilizerOrganicMix: 'Organic Mix',
    
    // Dosage Units
    kgPerAcre: 'kg per acre',
    tonsPerAcre: 'tons per acre',
    
    // Fertilizer Remarks (Primary)
    remarkNPK: 'Balanced fertilizer suitable for most crops. Apply during planting.',
    remarkUrea: 'High nitrogen content. Best applied during vegetative growth stage.',
    remarkDAP: 'Rich in phosphorus. Ideal for root development and flowering.',
    remarkPotash: 'Essential for fruit quality and disease resistance. Apply during fruiting.',
    remarkCompost: 'Organic option. Improves soil structure and nutrient retention.',
    remarkOrganicMix: 'Complete organic solution. Enhances soil health and crop quality.',
    
    // Alternative Remarks
    altRemarkNPK: 'Good alternative for balanced nutrition. Can be mixed with organic matter.',
    altRemarkUrea: 'Alternative nitrogen source. Apply in split doses for better efficiency.',
    altRemarkDAP: 'Alternative phosphorus source. Works well with organic amendments.',
    altRemarkPotash: 'Alternative potassium source. Good for fruit and flower development.',
    altRemarkCompost: 'Excellent organic alternative. Builds long-term soil fertility.',
    altRemarkOrganicMix: 'Sustainable alternative. Improves soil biodiversity and health.',
    
    // Suggestions Translations
    suggestionLowN: 'Consider adding nitrogen-rich organic matter like farmyard manure or green manure crops.',
    suggestionLowP: 'Phosphorus levels are low. Consider bone meal or rock phosphate as organic alternatives.',
    suggestionLowK: 'Potassium deficiency detected. Wood ash or banana peels can be used as organic potassium sources.',
    suggestionAcidic: 'Soil is acidic. Consider adding lime to raise pH level gradually.',
    suggestionAlkaline: 'Soil is alkaline. Consider adding sulfur or organic matter to lower pH.',
    suggestionLowMoisture: 'Low soil moisture. Ensure adequate irrigation before fertilizer application.',
    suggestionHighTemp: 'High temperature conditions. Apply fertilizers early morning or evening to avoid evaporation loss.',
    suggestionTomato: 'For tomatoes, consider side-dressing with compost during flowering stage.',
    suggestionRice: 'For rice, split application of nitrogen is recommended - 50% at planting, 25% at tillering, 25% at panicle initiation.',
    suggestionWheat: 'For wheat, apply phosphorus at sowing and nitrogen in split doses during growth stages.',
    suggestionCabbage: 'For cabbage, ensure adequate nitrogen for leaf development. Consider foliar feeding.',
    suggestionPotato: 'For potatoes, high potassium requirement. Apply potash at tuber formation stage.',
    suggestionCotton: 'For cotton, balanced NPK with micronutrients. Consider zinc and boron supplements.',
    suggestionDefault: 'Follow crop-specific nutrient management practices.',
    consultExpert: 'Consult agricultural expert',
    
    // Language
    language: 'Language',
    english: 'English',
    tamil: 'Tamil',
    
    // New Features Translations
    soilHealthScore: 'Soil Health Score',
    soilHealthExcellent: 'Excellent soil health!',
    soilHealthGood: 'Good but needs more organic matter.',
    soilHealthFair: 'Fair - requires soil improvement.',
    soilHealthPoor: 'Poor - immediate soil treatment needed.',
    
    pestRiskPredictor: 'Pest Risk Predictor',
    risk: 'Risk',
    pestRiskLow: 'Low',
    pestRiskMedium: 'Medium',
    pestRiskMediumHigh: 'Medium-High',
    pestRiskHigh: 'High',
    pestRiskLowMessage: 'Low pest risk. Regular monitoring recommended.',
    pestRiskLowRec: 'Continue normal pest management practices.',
    pestRiskHighMessage: 'High chance of fungal infections',
    pestRiskHighRec: 'Apply neem oil once a week. Ensure proper ventilation.',
    pestRiskMediumMessage: 'Moderate pest risk detected',
    pestRiskMediumRec: 'Increase monitoring frequency. Use organic pest control.',
    pestRiskMediumHighMessage: 'Moderate to high risk of pest attacks',
    pestRiskMediumHighRec: 'Apply preventive organic pesticides. Monitor daily.',
    pestRiskRiceHigh: 'High chance of blast disease and stem borer',
    pestRiskRiceRec: 'Apply neem oil and fungicides. Monitor for stem borer. Ensure proper water management.',
    pestRiskRiceMedium: 'Moderate risk of rice diseases',
    pestRiskRiceRecMedium: 'Monitor for leaf folder and diseases. Apply preventive measures.',
    pestRiskVegetableHigh: 'High chance of fungal infections and fruit borer',
    pestRiskVegetableRec: 'Apply neem oil once a week. Ensure proper ventilation. Monitor for fruit borer.',
    pestRiskVegetableMediumHigh: 'Moderate to high risk of pest attacks',
    pestRiskVegetableRecMedium: 'Apply preventive organic pesticides. Monitor daily for aphids and whitefly.',
    pestRiskCottonHigh: 'High risk of bollworm and whitefly',
    pestRiskCottonRec: 'Monitor for bollworm regularly. Apply Bt cotton or organic pesticides.',
    pestRiskCottonMedium: 'Moderate pest risk in cotton',
    pestRiskCottonRecMedium: 'Increase monitoring frequency. Use organic pest control.',
    
    waterUsageAlert: 'Water Usage Alert',
    waterRequirement: 'Water Requirement',
    waterVeryHigh: 'Very High',
    waterHigh: 'High',
    waterMediumHigh: 'Medium-High',
    waterMedium: 'Medium',
    waterLowMedium: 'Low-Medium',
    waterRice: 'Rice requires 1000-2000mm water. Ensure adequate irrigation.',
    waterSugarcane: 'Sugarcane needs 1200-2000mm water. Regular irrigation essential.',
    waterCotton: 'Cotton requires 500-800mm water. Monitor soil moisture regularly.',
    waterMaize: 'Maize needs 500-800mm water. Moderate irrigation sufficient.',
    waterWheat: 'Wheat requires 400-600mm water. Timely irrigation important.',
    waterTomato: 'Tomato needs 600-1000mm water. Consistent watering crucial.',
    waterPotato: 'Potato requires 500-700mm water. Avoid waterlogging.',
    waterOnion: 'Onion needs 600-800mm water. Moderate irrigation.',
    waterCarrot: 'Carrot requires 500-700mm water. Regular light watering.',
    waterCucumber: 'Cucumber needs 600-1000mm water. High water requirement.',
    waterWatermelon: 'Watermelon requires 500-800mm water. Consistent moisture needed.',
    waterBrinjal: 'Brinjal needs 600-1000mm water. Regular irrigation needed.',
    waterChilli: 'Chilli requires 500-800mm water. Moderate irrigation sufficient.',
    waterCabbage: 'Cabbage needs 600-800mm water. Consistent moisture important.',
    waterCauliflower: 'Cauliflower requires 600-800mm water. Regular watering needed.',
    waterDefault: 'Moderate water requirement. Monitor soil moisture.',
    
    compostSuggestion: 'Compost Suggestion',
    compostAlkaline: 'Alkaline Compost',
    compostAcidic: 'Acidic Compost',
    compostMoistureRetaining: 'Moisture-Retaining Compost',
    compostDrainage: 'Drainage-Improving Compost',
    compostBalanced: 'Balanced Compost',
    compostRiceAcidic: 'For rice/sugarcane: Add lime-rich compost or wood ash to raise pH. Use decomposed organic matter with calcium.',
    compostRice: 'For rice/sugarcane: Use well-decomposed farmyard manure and green manure crops for better yield.',
    compostTomatoAlkaline: 'For vegetables: Add acidic compost like pine needles, coffee grounds to lower pH.',
    compostTomatoMoisture: 'For vegetables: Add compost rich in organic matter (coconut coir, leaf mold) to improve water retention.',
    compostTomato: 'For vegetables: Use well-balanced compost (kitchen scraps, garden waste) to maintain soil health.',
    compostWheat: 'For cereals: Use farmyard manure and compost to improve soil structure and nutrient availability.',
    compostAlkalineSuggestion: 'Add lime-rich compost or wood ash to raise pH. Use decomposed organic matter with calcium.',
    compostAcidicSuggestion: 'Add acidic compost like pine needles, coffee grounds, or peat moss to lower pH.',
    compostMoistureSuggestion: 'Add compost rich in organic matter (coconut coir, leaf mold) to improve water retention.',
    compostDrainageSuggestion: 'Add compost with coarse materials (straw, wood chips) to improve drainage.',
    compostBalancedSuggestion: 'Use well-balanced compost (kitchen scraps, garden waste) to maintain soil health.',
    
    cropRotationAdvisor: 'Crop Rotation Advisor',
    rotationRice: 'After Rice → Good rotation crops: Pulses (Moong, Urad), Legumes, Mustard',
    rotationWheat: 'After Wheat → Good rotation crops: Pulses, Oilseeds, Vegetables',
    rotationTomato: 'After Tomato → Good rotation crops: Legumes, Corn, Leafy greens',
    rotationPotato: 'After Potato → Good rotation crops: Legumes, Cereals, Mustard',
    rotationCotton: 'After Cotton → Good rotation crops: Pulses, Cereals, Oilseeds',
    rotationMaize: 'After Maize → Good rotation crops: Legumes, Wheat, Vegetables',
    rotationSugarcane: 'After Sugarcane → Good rotation crops: Pulses, Legumes, Green manure crops',
    rotationBrinjal: 'After Brinjal → Good rotation crops: Legumes, Leafy vegetables, Root crops',
    rotationChilli: 'After Chilli → Good rotation crops: Legumes, Onion, Garlic',
    rotationCabbage: 'After Cabbage → Good rotation crops: Legumes, Root vegetables, Corn',
    rotationCauliflower: 'After Cauliflower → Good rotation crops: Legumes, Leafy greens, Beans',
    rotationCarrot: 'After Carrot → Good rotation crops: Legumes, Leafy vegetables, Onion',
    rotationOnion: 'After Onion → Good rotation crops: Legumes, Leafy vegetables, Root crops',
    rotationCucumber: 'After Cucumber → Good rotation crops: Legumes, Corn, Leafy greens',
    rotationWatermelon: 'After Watermelon → Good rotation crops: Legumes, Leafy vegetables, Root crops',
    rotationDefault: 'Rotate with legumes or different crop families to maintain soil health.',
    
    dailyFarmingTip: 'Daily Farming Tip',
    tipRice1: 'Maintain proper water level in rice fields (5-7cm)',
    tipRice2: 'Apply nitrogen in split doses for better efficiency',
    tipRice3: 'Control weeds regularly to prevent competition',
    tipRice4: 'Monitor for stem borer and leaf folder pests',
    tipTomato1: 'Stake tomato plants for better support and air circulation',
    tipTomato2: 'Water at base, avoid wetting leaves to prevent diseases',
    tipTomato3: 'Prune side shoots (suckers) regularly',
    tipTomato4: 'Harvest regularly to encourage more fruiting',
    tipWheat1: 'Apply phosphorus at sowing for root development',
    tipWheat2: 'Control weeds early with herbicides',
    tipWheat3: 'Monitor for rust and powdery mildew diseases',
    tipWheat4: 'Harvest when grains are hard and moisture is 20-25%',
    tipSugarcane1: 'Apply nitrogen in 3-4 split doses',
    tipSugarcane2: 'Earthing up at 45 and 90 days after planting',
    tipSugarcane3: 'Maintain adequate irrigation throughout growth',
    tipSugarcane4: 'Harvest at 10-12 months when Brix is 18-20%',
    tipCotton1: 'Monitor for bollworm and whitefly regularly',
    tipCotton2: 'Apply micronutrients (zinc, boron) for better yield',
    tipCotton3: 'Prune lower branches for better air circulation',
    tipCotton4: 'Harvest when bolls open and lint is fluffy',
    tipDefault1: 'Water plants early morning or evening to reduce evaporation',
    tipDefault2: 'Mulch around plants to retain moisture and suppress weeds',
    tipDefault3: 'Test soil pH regularly for optimal nutrient availability',
    tipDefault4: 'Use organic compost to improve soil structure',
    tipDefault5: 'Rotate crops annually to prevent pest buildup',
    tipDefault6: 'Monitor plants daily for early pest detection',
    tipDefault7: 'Prune regularly to promote healthy growth',
    tipDefault8: 'Use companion planting to naturally deter pests',
    tipDefault9: 'Maintain proper spacing for air circulation',
    tipDefault10: 'Harvest at peak maturity for best quality',
    
    plantGrowthStageTips: 'Plant Growth Stage Tips',
    seedlingStage: 'Seedling Stage',
    vegetativeStage: 'Vegetative Stage',
    floweringStage: 'Flowering Stage',
    harvestStage: 'Harvest Stage',
    stage: 'Stage',
    
    // Growth Stage Tips - Rice
    riceSeedling1: 'Maintain 2-3cm water level in nursery',
    riceSeedling2: 'Keep temperature 25-30°C for germination',
    riceSeedling3: 'Apply light nitrogen after 10 days',
    riceSeedling4: 'Protect from birds and pests',
    riceVegetative1: 'Maintain 5-7cm water depth in field',
    riceVegetative2: 'Apply nitrogen in split doses (50% at planting, 25% at tillering)',
    riceVegetative3: 'Control weeds regularly',
    riceVegetative4: 'Monitor for stem borer and leaf folder',
    riceFlowering1: 'Critical water stage - maintain 5-10cm water',
    riceFlowering2: 'Apply remaining 25% nitrogen at panicle initiation',
    riceFlowering3: 'Avoid water stress during flowering',
    riceFlowering4: 'Monitor for blast disease',
    riceHarvest1: 'Drain water 10-15 days before harvest',
    riceHarvest2: 'Harvest when 80% grains turn golden yellow',
    riceHarvest3: 'Harvest in morning when moisture is 20-22%',
    riceHarvest4: 'Dry properly to 14% moisture for storage',
    
    // Growth Stage Tips - Tomato
    tomatoSeedling1: 'Start seeds in nursery trays with well-drained soil',
    tomatoSeedling2: 'Maintain 20-25°C temperature',
    tomatoSeedling3: 'Transplant after 25-30 days when 4-5 leaves appear',
    tomatoSeedling4: 'Harden seedlings before transplanting',
    tomatoVegetative1: 'Stake plants for support',
    tomatoVegetative2: 'Apply nitrogen-rich fertilizer for leaf growth',
    tomatoVegetative3: 'Prune side shoots (suckers) regularly',
    tomatoVegetative4: 'Water at base, avoid wetting leaves',
    tomatoFlowering1: 'Apply phosphorus for flower and fruit set',
    tomatoFlowering2: 'Maintain consistent moisture - avoid stress',
    tomatoFlowering3: 'Hand pollination may help in low humidity',
    tomatoFlowering4: 'Monitor for blossom end rot',
    tomatoHarvest1: 'Harvest when fruits are firm and fully colored',
    tomatoHarvest2: 'Harvest in early morning',
    tomatoHarvest3: 'Pick regularly to encourage more fruiting',
    tomatoHarvest4: 'Handle gently to avoid bruising',
    
    // Growth Stage Tips - Wheat
    wheatSeedling1: 'Sow at proper depth (5-6cm)',
    wheatSeedling2: 'Maintain soil moisture for germination',
    wheatSeedling3: 'Apply phosphorus at sowing',
    wheatSeedling4: 'Protect from birds',
    wheatVegetative1: 'Apply first dose of nitrogen at tillering stage',
    wheatVegetative2: 'Control weeds with herbicides',
    wheatVegetative3: 'Ensure adequate spacing (20-25cm rows)',
    wheatVegetative4: 'Monitor for rust and powdery mildew',
    wheatFlowering1: 'Apply second nitrogen dose at boot stage',
    wheatFlowering2: 'Avoid water stress during flowering',
    wheatFlowering3: 'Monitor for aphids and diseases',
    wheatFlowering4: 'Support with potash for grain filling',
    wheatHarvest1: 'Harvest when grains are hard and moisture is 20-25%',
    wheatHarvest2: 'Harvest in early morning',
    wheatHarvest3: 'Thresh immediately after harvest',
    wheatHarvest4: 'Dry to 12% moisture for storage',
    
    // Growth Stage Tips - Sugarcane
    sugarcaneSeedling1: 'Plant setts with 2-3 buds',
    sugarcaneSeedling2: 'Maintain soil moisture for sprouting',
    sugarcaneSeedling3: 'Apply basal dose of NPK',
    sugarcaneSeedling4: 'Control weeds early',
    sugarcaneVegetative1: 'Apply nitrogen in 3-4 split doses',
    sugarcaneVegetative2: 'Earthing up at 45 and 90 days',
    sugarcaneVegetative3: 'Maintain adequate irrigation',
    sugarcaneVegetative4: 'Monitor for top borer and red rot',
    sugarcaneFlowering1: 'Reduce nitrogen, increase potash',
    sugarcaneFlowering2: 'Maintain soil moisture',
    sugarcaneFlowering3: 'Remove flower stalks if not needed',
    sugarcaneFlowering4: 'Monitor for pests and diseases',
    sugarcaneHarvest1: 'Harvest at 10-12 months when Brix is 18-20%',
    sugarcaneHarvest2: 'Cut close to ground level',
    sugarcaneHarvest3: 'Harvest in early morning',
    sugarcaneHarvest4: 'Crush within 24-48 hours for best quality',
    
    // Growth Stage Tips - Cotton
    cottonSeedling1: 'Sow at proper depth (2-3cm)',
    cottonSeedling2: 'Maintain soil temperature 20-25°C',
    cottonSeedling3: 'Thin to proper spacing after emergence',
    cottonSeedling4: 'Control early season pests',
    cottonVegetative1: 'Apply nitrogen for vegetative growth',
    cottonVegetative2: 'Prune lower branches and leaves',
    cottonVegetative3: 'Monitor for bollworm and whitefly',
    cottonVegetative4: 'Maintain proper plant spacing',
    cottonFlowering1: 'Apply phosphorus and potash for boll development',
    cottonFlowering2: 'Critical stage - avoid water stress',
    cottonFlowering3: 'Monitor for pink bollworm',
    cottonFlowering4: 'Support with micronutrients (zinc, boron)',
    cottonHarvest1: 'Harvest when bolls open and lint is fluffy',
    cottonHarvest2: 'Pick in dry weather conditions',
    cottonHarvest3: 'Harvest in multiple pickings',
    cottonHarvest4: 'Store in dry, clean place',
    
    // Default Growth Stage Tips
    defaultSeedling1: 'Maintain consistent moisture - not too wet, not too dry',
    defaultSeedling2: 'Provide gentle light - avoid direct harsh sunlight',
    defaultSeedling3: 'Keep temperature stable between 20-25°C',
    defaultSeedling4: 'Use diluted fertilizer if needed',
    defaultVegetative1: 'Increase nitrogen for leaf growth',
    defaultVegetative2: 'Ensure adequate spacing for air circulation',
    defaultVegetative3: 'Water deeply but less frequently',
    defaultVegetative4: 'Monitor for early signs of pests',
    defaultFlowering1: 'Increase phosphorus for flower development',
    defaultFlowering2: 'Maintain consistent watering schedule',
    defaultFlowering3: 'Avoid overhead watering to prevent flower damage',
    defaultFlowering4: 'Support plants if needed (staking)',
    defaultHarvest1: 'Reduce watering before harvest',
    defaultHarvest2: 'Harvest in early morning for best quality',
    defaultHarvest3: 'Check for maturity indicators specific to crop',
    defaultHarvest4: 'Handle produce gently to avoid bruising',
    
    aiIrrigationAlert: 'AI Irrigation Alert',
    irrigationAlertRain: 'Rain expected in 2 hours — Avoid watering now.',
    irrigationAlertSafe: 'No rain expected. Safe to irrigate.',
    in2Hours: '2 hours',
    next24Hours: 'next 24 hours',
    
    estimatedCost: '💰 Estimated Cost',
    perKg: 'per kg',
    approx: 'Approx',
    for: 'for',
    hectares: 'hectares',
    
    // YouTube Videos
    learningVideos: '📺 Learning Videos',
    videoTutorials: 'Video Tutorials',
    learnHowToFarm: 'Learn How to Farm',
    watchOnYouTube: 'Watch on YouTube',
    videoCategory: 'Category',
    videoDuration: 'Duration',
    noVideosAvailable: 'No videos available for this crop',
    loadingVideos: 'Loading video recommendations...',
    videoDescription: 'Description',
    farmingTutorials: 'Farming Tutorials',
    completeGuide: 'Complete Guide',
    pestControl: 'Pest Control',
    diseaseManagement: 'Disease Management',
    organicFarming: 'Organic Farming',
    cultivationTechnique: 'Cultivation Technique',
    harvesting: 'Harvesting',
    irrigation: 'Irrigation',
    advancedMethods: 'Advanced Methods',
    postHarvest: 'Post-Harvest'
  },
  ta: {
    // Navigation
    home: 'வீடு',
    about: 'பற்றி',
    planner: 'உர பரிந்துரை',
    weather: 'வானிலை',
    calendar: 'பயிர் காலண்டர்',
    dashboard: 'டாஷ்போர்டு',
    history: 'வரலாறு',
    logout: 'வெளியேற',
    tutorials: 'பயிற்சிகள்',
    
    // Login
    login: 'உள்நுழை',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    loginButton: 'உள்நுழை',
    loginError: 'தவறான அறிமுகங்கள்',
    loginSuccess: 'வெற்றிகரமாக உள்நுழைந்தது',
    
    // Home
    welcome: 'உர பரிந்துரை அமைப்புக்கு வரவேற்கிறோம்',
    description: 'உங்கள் பயிர்களுக்கு AI-இயக்கப்பட்ட உர பரிந்துரைகளைப் பெறுங்கள்',
    
    // Planner
    fertilizerPlanner: 'உர பரிந்துரை திட்டமிடுபவர்',
    n: 'நைட்ரஜன் (N)',
    p: 'பாஸ்பரஸ் (P)',
    k: 'பொட்டாசியம் (K)',
    temperature: 'வெப்பநிலை (°C)',
    humidity: 'ஈரப்பதம் (%)',
    ph: 'pH அளவு',
    moisture: 'ஈரப்பதம் (%)',
    crop: 'பயிர் வகை',
    getRecommendation: 'பரிந்துரையைப் பெறு',
    recommendation: 'பரிந்துரை',
    fertilizer: 'உர',
    dosage: 'மருந்தளவு',
    remarks: 'குறிப்புகள்',
    downloadPDF: 'PDF பதிவிறக்க',
    selectCrop: 'பயிரைத் தேர்ந்தெடு',
    soilType: 'மண் வகை',
    hectareArea: 'ஹெக்டேர் பரப்பளவு',
    selectSoilType: 'மண் வகையைத் தேர்ந்தெடு',
    primaryRecommendation: 'முதன்மை பரிந்துரை',
    alternativeOptions: 'மாற்று விருப்பங்கள்',
    alternativeSubtitle: 'முதன்மை பரிந்துரைக்கு பதிலாக, இந்த மாற்று விருப்பங்களையும் நீங்கள் கருத்தில் கொள்ளலாம்:',
    alternative: 'மாற்று',
    additionalSuggestions: 'கூடுதல் பரிந்துரைகள் மற்றும் குறிப்புகள்',
    
    // Dashboard
    modelAccuracy: 'மாதிரி துல்லியம்',
    accuracy: 'துல்லியம்',
    precision: 'துல்லியம்',
    recall: 'நினைவு',
    f1Score: 'F1-ஸ்கோர்',
    
    // History
    recommendationHistory: 'பரிந்துரை வரலாறு',
    timestamp: 'நேர முத்திரை',
    inputs: 'உள்ளீடுகள்',
    noHistory: 'பரிந்துரை வரலாறு கிடைக்கவில்லை',
    searchHistory: 'பயிர், உரம் அல்லது மண் வகையால் தேட...',
    sortBy: 'வரிசைப்படுத்து',
    newestFirst: 'புதியது முதலில்',
    oldestFirst: 'பழையது முதலில்',
    showing: 'காட்டுகிறது',
    of: 'இல்',
    recommendations: 'பரிந்துரைகள்',
    noResults: 'முடிவுகள் கிடைக்கவில்லை',
    
    // About
    aboutTitle: 'இந்த அமைப்பு பற்றி',
    aboutContent: 'இந்த அமைப்பு மண் நிலைகள் மற்றும் சுற்றுச்சூழல் காரணிகளின் அடிப்படையில் உங்கள் பயிர்களுக்கு சிறந்த உரத்தை பரிந்துரைக்க இயந்திர கற்றல் (முடிவு மர வகைப்படுத்தி) பயன்படுத்துகிறது.',
    
    // Weather
    weatherInfo: 'வானிலை தகவல்',
    weatherPlaceholder: 'வானிலை தகவலைப் பெற இடத்தை உள்ளிடவும்',
    location: 'இடம்',
    enterLocation: 'நகரம் அல்லது பகுதி பெயரை உள்ளிடவும்',
    selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    getWeather: 'வானிலையைப் பெறு',
    loading: 'ஏற்றுகிறது...',
    windSpeed: 'காற்று வேகம்',
    rainfall: 'மழை',
    forecast: '3-நாள் முன்னறிவிப்பு',
    farmingTips: 'விவசாய குறிப்புகள்',
    highTempTip: 'அதிக வெப்பநிலை கண்டறியப்பட்டது. பயிர்களுக்கு போதுமான நீர்ப்பாசனம் மற்றும் நிழல் உறுதி செய்யவும்.',
    rainfallTip: 'மழை எதிர்பார்க்கப்படுகிறது. கடும் மழையின் போது உரம் பயன்படுத்துவதைத் தவிர்க்கவும்.',
    highHumidityTip: 'அதிக ஈரப்பதம் நோய் அபாயத்தை அதிகரிக்கலாம். பயிர்களை நெருக்கமாக கண்காணிக்கவும்.',
    idealConditionsTip: 'விவசாய நடவடிக்கைகளுக்கு சிறந்த வானிலை நிலைகள்.',
    
    // Crop Calendar
    cropCalendar: 'பயிர் காலண்டர் மற்றும் பருவ வழிகாட்டி',
    calendarSubtitle: 'எப்போது நடவு செய்ய வேண்டும், எப்போது அறுவடை செய்ய வேண்டும், மற்றும் வானிலையிலிருந்து உங்கள் பயிர்களை எவ்வாறு பாதுகாக்க வேண்டும் என்பதை அறிக',
    selectSeason: 'வளரும் பருவத்தைத் தேர்ந்தெடு',
    kharif: 'காரிப் (மழைக்காலம்)',
    rabi: 'ராபி (குளிர்காலம்)',
    zaid: 'ஜைத் (கோடைகாலம்)',
    kharifMonths: 'ஜூன் - அக்டோபர்',
    rabiMonths: 'நவம்பர் - மார்ச்',
    zaidMonths: 'மார்ச் - ஜூன்',
    cropsForSeason: 'பயிர்கள்',
    plantingTime: 'நடவு நேரம்',
    harvestTime: 'அறுவடை நேரம்',
    duration: 'பயிர் காலம்',
    viewDetails: 'விவரங்களைக் காண்க',
    details: 'விவரங்கள்',
    rainfallRequirements: 'மழை தேவைகள்',
    idealRainfall: 'வெற்றிகரமான மழை',
    harmfulRainfall: 'தீங்கு விளைவிக்கும் மழை நிலைகள்',
    protectionMeasures: 'பாதுகாப்பு நடவடிக்கைகள்',
    cultivationTips: 'சாகுபடி குறிப்புகள்',
    checkRainfallImpact: 'மழையின் தாக்கத்தைச் சரிபார்க்க',
    enterRainfall: 'எதிர்பார்க்கப்படும் மழையை உள்ளிடவும்',
    protection: 'பாதுகாப்பு',
    excessiveRainfall: '⚠️ அதிக மழை எச்சரிக்கை',
    insufficientRainfall: '⚠️ போதுமான மழை இல்லை',
    needIrrigation: 'நீர்ப்பாசனம் தேவை. போதுமான நீர் வழங்கலை உறுதி செய்யவும்.',
    generalTips: 'பொது விவசாய குறிப்புகள்',
    rainfallManagement: 'மழை மேலாண்மை',
    temperatureControl: 'வெப்பநிலை கட்டுப்பாடு',
    cropRotation: 'பயிர் சுழற்சி',
    irrigationTiming: 'நீர்ப்பாசன நேரம்',
    rainfallTip: 'மழை வடிவங்களை கண்காணிக்கவும். அதிக மழை நீர் தேங்குதல் மற்றும் நோயை ஏற்படுத்தும். சரியான வடிகால் உறுதி செய்யவும்.',
    temperatureTip: 'தீவிர வெப்பநிலைகள் பயிர்களில் அழுத்தத்தை ஏற்படுத்தும். நிழல் வலைகள், மல்ச்சிங் பயன்படுத்தவும் அல்லது நடவு நேரங்களை சரிசெய்யவும்.',
    rotationTip: 'மண் வளத்தை பராமரிக்க, பூச்சிகளை குறைக்க, மற்றும் ஊட்டச்சத்து குறைவை தடுக்க பயிர்களை சுழற்றவும்.',
    irrigationTip: 'பயிர்களை காலை அல்லது மாலையில் நீர்ப்பாசனம் செய்யவும். ஆவியாதல் மூலம் நீர் இழப்பை தடுக்க நடுப்பகல் நீர்ப்பாசனத்தை தவிர்க்கவும்.',
    
    // Month names
    juneJuly: 'ஜூன் - ஜூலை',
    sepOct: 'செப்டம்பர் - அக்டோபர்',
    mayJune: 'மே - ஜூன்',
    octDec: 'அக்டோபர் - டிசம்பர்',
    decJan: 'டிசம்பர் - ஜனவரி',
    novDec: 'நவம்பர் - டிசம்பர்',
    aprMay: 'ஏப்ரல் - மே',
    janFeb: 'ஜனவரி - பிப்ரவரி',
    mayJun: 'மே - ஜூன்',
    mayJul: 'மே - ஜூலை',
    octNov: 'அக்டோபர் - நவம்பர்',
    febMar: 'பிப்ரவரி - மார்ச்',
    marApr: 'மார்ச் - ஏப்ரல்',
    
    // Crop-specific rainfall warnings
    riceHarmfulRain: 'பூக்கும் காலத்தில் கடும் மழை (நடவு செய்த 40-50 நாட்களுக்குப் பிறகு) பானிக்கிள்களை சேதப்படுத்தும். 3 நாட்களுக்கு மேல் நீர் தேங்குதல் தாவரங்களை கொல்லும்.',
    riceProtection: 'சரியான வடிகால் பராமரிக்கவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். முதிர்ச்சியின் போது கடும் மழை கணிக்கப்பட்டால் ஆரம்பத்தில் அறுவடை செய்யவும்.',
    riceTip1: 'நாற்றங்காலில் விதைத்த 20-25 நாட்களுக்குப் பிறகு நாற்றுகளை நடவு செய்யவும்',
    riceTip2: 'வளர்ச்சி நிலையில் 5-7 செமீ நீர் ஆழத்தை பராமரிக்கவும்',
    riceTip3: 'நைட்ரஜனை பிரிக்கப்பட்ட அளவுகளில் பயன்படுத்தவும்: 50% அடிப்படை, 25% தில்லிங் நிலையில், 25% பானிக்கிள் தொடக்கத்தில்',
    
    wheatHarmfulRain: 'தானிய நிரப்புதல் மற்றும் முதிர்ச்சியின் போது மழை தாழ்வு, முளைத்தல் மற்றும் துரு மற்றும் பிளைட் போன்ற பூஞ்சை நோய்களை ஏற்படுத்தும்.',
    wheatProtection: 'கடும் மழைக்கு முன் அறுவடை செய்யவும். நோய் எதிர்ப்பு வகைகளை பயன்படுத்தவும். தலைப்பு காலத்தில் மழை தொடர்ந்தால் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும்.',
    wheatTip1: 'சிறந்த விளைச்சலுக்கு சரியான நேரத்தில் விதைக்கவும் (நவம்பர் நடுப்பகுதி முதல் டிசம்பர் ஆரம்பம் வரை)',
    wheatTip2: 'கிரீடம் வேர் தொடக்கத்தில் முதல் நீர்ப்பாசனம் செய்யவும் (விதைத்த 20-25 நாட்களுக்குப் பிறகு)',
    wheatTip3: 'தோன்றுவதற்கு முன் களைக்கொல்லிகளால் களைகளை கட்டுப்படுத்தவும்',
    
    tomatoHarmfulRain: 'கடும் மழை பழம் விரிசல், மலர் வீழ்ச்சி மற்றும் பிளைட், பாக்டீரியா புள்ளி மற்றும் பழம் அழுகல் நோய்களின் அபாயத்தை அதிகரிக்கும்.',
    tomatoProtection: 'நல்ல வடிகால் கொண்ட உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். கடும் மழையின் போது தாவரங்களை மூடவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும்.',
    tomatoTip1: 'சிறந்த ஆதரவு மற்றும் காற்று சுழற்சிக்காக தாவரங்களை கட்டவும் அல்லது கூண்டில் வைக்கவும்',
    tomatoTip2: 'மண் தெறிப்பை தடுக்க மற்றும் ஈரப்பதத்தை பராமரிக்க தாவரங்களைச் சுற்றி மல்ச் செய்யவும்',
    tomatoTip3: 'நோயை தடுக்க அடிப்பகுதியில் நீர்ப்பாசனம் செய்யவும், மேலே நீர்ப்பாசனத்தை தவிர்க்கவும்',
    
    cottonHarmfulRain: 'போல் உருவாக்கத்தின் போது அதிக மழை போல் அழுகல், வீழ்ச்சி மற்றும் நார் தரத்தை குறைக்கும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    cottonProtection: 'சரியான வடிகால் உறுதி செய்யவும். மேடு மற்றும் பள்ளம் அமைப்பை பயன்படுத்தவும். கடும் மழைக்கு முன் திறந்த போல்களை அறுவடை செய்யவும்.',
    cottonTip1: 'பரிந்துரைக்கப்பட்ட இடைவெளியில் நடவு செய்யவும் (வரிசைகளுக்கு இடையே 60-90 செமீ)',
    cottonTip2: 'நடவு செய்த முதல் 40-50 நாட்களில் களைகளை கட்டுப்படுத்தவும்',
    cottonTip3: 'சிறந்த போல் வளர்ச்சிக்காக பொட்டாசியத்தில் அழுத்தத்துடன் சமநிலை NPK பயன்படுத்தவும்',
    
    // Additional Crop Details
    cropDetailsNotAvailable: 'இந்த பயிருக்கான விரிவான தகவல் புதுப்பிக்கப்படுகிறது. தயவுசெய்து விரைவில் மீண்டும் சரிபார்க்கவும்.',
    
    // Maize
    maizeHarmfulRain: 'பூக்கும் மற்றும் தானிய நிரப்பும் காலத்தில் கடும் மழை தாழ்வு மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    maizeProtection: 'சரியான வடிகால் உறுதி செய்யவும். மேடு நடவு பயன்படுத்தவும். முதிர்ச்சியின் போது கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    maizeTip1: 'வரிசைகளுக்கு இடையே 60-75 செமீ மற்றும் தாவரங்களுக்கு இடையே 20-25 செமீ இடைவெளியில் நடவு செய்யவும்',
    maizeTip2: 'நைட்ரஜனை பிரிக்கப்பட்ட அளவுகளில் பயன்படுத்தவும்: 50% நடவு செய்யும் போது, 25% முழங்கால் உயர நிலையில், 25% தாசலிங் நிலையில்',
    maizeTip3: 'நடவு செய்த முதல் 30-40 நாட்களில் களைகளை கட்டுப்படுத்தவும்',
    
    // Sugarcane
    sugarcaneHarmfulRain: 'அதிக மழை நீர் தேங்குதல், வேர் அழுகல் மற்றும் சர்க்கரை உள்ளடக்கத்தை குறைக்கும். வெள்ளம் பயிரை சேதப்படுத்தும்.',
    sugarcaneProtection: 'சரியான வடிகால் சேனல்களை பராமரிக்கவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். நீர் தேங்குவதை தவிர்க்கவும்.',
    sugarcaneTip1: '90-120 செமீ இடைவெளியில் பள்ளங்களில் செட்டுகளை நடவு செய்யவும்',
    sugarcaneTip2: 'நடவு செய்த உடனே முதல் நீர்ப்பாசனம் செய்யவும், பின்னர் 10-15 நாள் இடைவெளியில்',
    sugarcaneTip3: 'நடவு செய்த 90-120 நாட்களுக்குப் பிறகு மண் சேர்ப்பு செய்ய வேண்டும்',
    
    // Groundnut
    groundnutHarmfulRain: 'போட் உருவாக்கத்தின் போது கடும் மழை போட் அழுகல் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் வேர் வளர்ச்சியை பாதிக்கும்.',
    groundnutProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். போட் அழுகலை தடுக்க கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    groundnutTip1: 'வரிசைகளுக்கு இடையே 30-45 செமீ மற்றும் தாவரங்களுக்கு இடையே 10-15 செமீ இடைவெளியில் விதைகளை நடவு செய்யவும்',
    groundnutTip2: 'சிறந்த போட் வளர்ச்சிக்காக பூக்கும் நிலையில் ஜிப்சம் பயன்படுத்தவும்',
    groundnutTip3: 'நடவு செய்த முதல் 30-40 நாட்களில் களைகளை கட்டுப்படுத்தவும்',
    
    // Soybean
    soybeanHarmfulRain: 'பூக்கும் மற்றும் போட் நிரப்பும் காலத்தில் அதிக மழை தாழ்வு மற்றும் போட் வீழ்ச்சியை ஏற்படுத்தும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    soybeanProtection: 'சரியான வடிகால் பராமரிக்கவும். நோய் எதிர்ப்பு வகைகளை பயன்படுத்தவும். கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    soybeanTip1: 'வரிசைகளுக்கு இடையே 45-60 செமீ இடைவெளியில் விதைகளை நடவு செய்யவும்',
    soybeanTip2: 'நடவு செய்வதற்கு முன் விதைகளை ரைசோபியம் கலாச்சாரத்துடன் தடவவும்',
    soybeanTip3: 'சிறந்த வேர் மற்றும் போட் வளர்ச்சிக்காக நடவு செய்யும் போது பாஸ்பரஸ் பயன்படுத்தவும்',
    
    // Turmeric
    turmericHarmfulRain: 'அதிக மழை ரைசோம் அழுகல் மற்றும் பூஞ்சை நோய்களை ஏற்படுத்தும். நீர் தேங்குதல் பயிரை சேதப்படுத்தும்.',
    turmericProtection: 'சிறந்த வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். மழைக்காலத்தில் தடுப்பு முறையில் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும்.',
    turmericTip1: '30-45 செமீ இடைவெளியில் நன்கு தயாரிக்கப்பட்ட படுக்கைகளில் ரைசோம்களை நடவு செய்யவும்',
    turmericTip2: 'கரிம எருவு மற்றும் சமநிலை NPK உரங்களை பயன்படுத்தவும்',
    turmericTip3: 'ஈரப்பதத்தை பாதுகாக்க மற்றும் களைகளை கட்டுப்படுத்த புலத்தை மல்ச் செய்யவும்',
    
    // Ginger
    gingerHarmfulRain: 'கடும் மழை ரைசோம் அழுகல், பாக்டீரியா வில்ட் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் மிகவும் தீங்கு விளைவிக்கும்.',
    gingerProtection: 'சிறந்த வடிகால் அவசியம். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகள் மற்றும் பாக்டீரியாக்கொல்லிகளை பயன்படுத்தவும்.',
    gingerTip1: '30-40 செமீ இடைவெளியில் நன்கு வடிகால் செய்யப்பட்ட படுக்கைகளில் ரைசோம்களை நடவு செய்யவும்',
    gingerTip2: 'கரிம எருவு மற்றும் சமநிலை உரங்களை பயன்படுத்தவும்',
    gingerTip3: 'ஈரப்பதத்தை பாதுகாக்க மற்றும் மண் தெறிப்பை தடுக்க கனமாக மல்ச் செய்யவும்',
    
    // Barley
    barleyHarmfulRain: 'தானிய நிரப்புதல் மற்றும் முதிர்ச்சியின் போது மழை தாழ்வு மற்றும் தானிய தரத்தை குறைக்கும்.',
    barleyProtection: 'கடும் மழைக்கு முன் அறுவடை செய்யவும். தாழ்வு எதிர்ப்பு வகைகளை பயன்படுத்தவும். சரியான வடிகால் உறுதி செய்யவும்.',
    barleyTip1: 'சிறந்த விளைச்சலுக்கு சரியான நேரத்தில் விதைக்கவும் (நவம்பர் நடுப்பகுதி)',
    barleyTip2: 'கிரீடம் வேர் தொடக்க நிலையில் முதல் நீர்ப்பாசனம் செய்யவும்',
    barleyTip3: 'தோன்றுவதற்கு முன் களைக்கொல்லிகளால் களைகளை கட்டுப்படுத்தவும்',
    
    // Mustard
    mustardHarmfulRain: 'பூக்கும் மற்றும் போட் உருவாக்கத்தின் போது கடும் மழை போட் உடைத்தல் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும்.',
    mustardProtection: 'கடும் மழைக்கு முன் அறுவடை செய்யவும். போட் உடைத்தல் எதிர்ப்பு வகைகளை பயன்படுத்தவும். சரியான வடிகால் உறுதி செய்யவும்.',
    mustardTip1: 'வரிசைகளுக்கு இடையே 30-45 செமீ இடைவெளியில் விதைகளை விதைக்கவும்',
    mustardTip2: 'ரோசெட் நிலையில் முதல் நீர்ப்பாசனம் செய்யவும் (விதைத்த 30-35 நாட்களுக்குப் பிறகு)',
    mustardTip3: 'பூக்கும் நிலையில் அஃபிட்கள் மற்றும் பிற பூச்சிகளை கட்டுப்படுத்தவும்',
    
    // Potato
    potatoHarmfulRain: 'அதிக மழை கிழங்கு அழுகல், தாமத பிளைட் நோய் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் கிழங்குகளை சேதப்படுத்தும்.',
    potatoProtection: 'சிறந்த வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும். கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    potatoTip1: 'வரிசைகளுக்கு இடையே 60-75 செமீ மற்றும் தாவரங்களுக்கு இடையே 20-25 செமீ இடைவெளியில் விதை கிழங்குகளை நடவு செய்யவும்',
    potatoTip2: 'நடவு செய்த உடனே முதல் நீர்ப்பாசனம் செய்யவும்',
    potatoTip3: 'நடவு செய்த 30-40 நாட்களுக்குப் பிறகு மண் சேர்ப்பு செய்ய வேண்டும்',
    
    // Onion
    onionHarmfulRain: 'பல்ப் உருவாக்கத்தின் போது கடும் மழை பல்ப் அழுகல் மற்றும் சேமிப்பு தரத்தை குறைக்கும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    onionProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். சேமிப்பதற்கு முன் சரியாக அறுவடை செய்து உலர்த்தவும்.',
    onionTip1: 'வரிசைகளுக்கு இடையே 15-20 செமீ மற்றும் தாவரங்களுக்கு இடையே 10 செமீ இடைவெளியில் நாற்றுகளை நடவு செய்யவும்',
    onionTip2: 'நடவு செய்த உடனே முதல் நீர்ப்பாசனம் செய்யவும்',
    onionTip3: 'சிறந்த பல்ப் தரத்திற்காக அறுவடைக்கு 15-20 நாட்களுக்கு முன் நீர்ப்பாசனத்தை நிறுத்தவும்',
    
    // Carrot
    carrotHarmfulRain: 'அதிக மழை வேர் பிளவு மற்றும் அழுகலை ஏற்படுத்தும். நீர் தேங்குதல் வேர் வளர்ச்சியை பாதிக்கும்.',
    carrotProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். பிளவை தடுக்க கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    carrotTip1: 'வரிசைகளுக்கு இடையே 30-45 செமீ இடைவெளியில் நன்கு தயாரிக்கப்பட்ட படுக்கைகளில் விதைகளை விதைக்கவும்',
    carrotTip2: 'நாற்றுகள் 5-7 செமீ உயரமாக இருக்கும்போது 5-8 செமீ இடைவெளிக்கு மெல்லியதாக்கவும்',
    carrotTip3: 'சமநிலை உரங்களை பயன்படுத்தவும், அதிக நைட்ரஜனை தவிர்க்கவும்',
    
    // Cabbage
    cabbageHarmfulRain: 'கடும் மழை தலை பிளவு மற்றும் நோய் அபாயத்தை அதிகரிக்கும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    cabbageProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். முடிந்தால் கடும் மழையின் போது தலைகளை மூடவும்.',
    cabbageTip1: '45-60 செமீ இடைவெளியில் நாற்றுகளை நடவு செய்யவும்',
    cabbageTip2: 'நடவு செய்த உடனே முதல் நீர்ப்பாசனம் செய்யவும்',
    cabbageTip3: 'இலை வளர்ச்சிக்கு போதுமான நைட்ரஜனை உறுதி செய்யவும்',
    
    // Cauliflower
    cauliflowerHarmfulRain: 'அதிக மழை கர்ட் அழுகல் மற்றும் தரத்தை குறைக்கும். நீர் தேங்குதல் தாவரத்தை சேதப்படுத்தும்.',
    cauliflowerProtection: 'சிறந்த வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். கடும் மழையின் போது கர்ட்களை மூடவும்.',
    cauliflowerTip1: '45-60 செமீ இடைவெளியில் நாற்றுகளை நடவு செய்யவும்',
    cauliflowerTip2: 'நடவு செய்த உடனே முதல் நீர்ப்பாசனம் செய்யவும்',
    cauliflowerTip3: 'வெயில் மற்றும் மழையிலிருந்து பாதுகாக்க கர்ட் மீது இலைகளை கட்டவும்',
    
    // Cucumber
    cucumberHarmfulRain: 'கடும் மழை பழம் அழுகல், பவுடரி மில்ட்யூ மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    cucumberProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும். கொடிகளுக்கு ஆதரவு வழங்கவும்.',
    cucumberTip1: 'வரிசைகளுக்கு இடையே 90-120 செமீ இடைவெளியில் விதைகளை விதைக்கவும்',
    cucumberTip2: 'சிறந்த வளர்ச்சி மற்றும் பழ தரத்திற்காக ட்ரெல்லிஸ் அல்லது ஆதரவு வழங்கவும்',
    cucumberTip3: 'சமநிலை உரங்களை பயன்படுத்தவும், பழம் காய்க்கும் போது போதுமான நீரை உறுதி செய்யவும்',
    
    // Watermelon
    watermelonHarmfulRain: 'அதிக மழை பழம் பிளவு, அழுகல் மற்றும் சர்க்கரை உள்ளடக்கத்தை குறைக்கும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    watermelonProtection: 'சிறந்த வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். கடும் மழைக்கு முன் அறுவடை செய்யவும். முடிந்தால் பழங்களை மூடவும்.',
    watermelonTip1: 'வரிசைகளுக்கு இடையே 150-200 செமீ இடைவெளியில் விதைகளை விதைக்கவும்',
    watermelonTip2: 'விதைத்த உடனே முதல் நீர்ப்பாசனம் செய்யவும்',
    watermelonTip3: 'சிறந்த சர்க்கரை உள்ளடக்கத்திற்காக அறுவடைக்கு 10-15 நாட்களுக்கு முன் நீர்ப்பாசனத்தை குறைக்கவும்',
    
    // Pumpkin
    pumpkinHarmfulRain: 'கடும் மழை பழம் அழுகல் மற்றும் நோய் அபாயத்தை அதிகரிக்கும். நீர் தேங்குதல் தாவரத்தை சேதப்படுத்தும்.',
    pumpkinProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். கொடிகளுக்கு ஆதரவு வழங்கவும். கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    pumpkinTip1: 'வரிசைகளுக்கு இடையே 150-200 செமீ இடைவெளியில் விதைகளை விதைக்கவும்',
    pumpkinTip2: 'ஆதரவு வழங்கவும் அல்லது தரையில் பின்தொடர அனுமதிக்கவும்',
    pumpkinTip3: 'சமநிலை உரங்களை பயன்படுத்தவும், பழம் காய்க்கும் போது போதுமான நீரை உறுதி செய்யவும்',
    
    // Brinjal
    brinjalHarmfulRain: 'அதிக மழை பழம் அழுகல், பாக்டீரியா வில்ட் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    brinjalProtection: 'சிறந்த வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகள் மற்றும் பாக்டீரியாக்கொல்லிகளை பயன்படுத்தவும்.',
    brinjalTip1: '60-75 செமீ இடைவெளியில் நாற்றுகளை நடவு செய்யவும்',
    brinjalTip2: 'சிறந்த ஆதரவு மற்றும் காற்று சுழற்சிக்காக தாவரங்களை கட்டவும்',
    brinjalTip3: 'சமநிலை உரங்களை பயன்படுத்தவும், பழம் காய்க்கும் போது போதுமான நீரை உறுதி செய்யவும்',
    
    // Chilli
    chilliHarmfulRain: 'கடும் மழை பழம் வீழ்ச்சி, அந்த்ராக்னோஸ் மற்றும் விளைச்சல் குறைவை ஏற்படுத்தும். நீர் தேங்குதல் வேர்களை சேதப்படுத்தும்.',
    chilliProtection: 'நல்ல வடிகால் உறுதி செய்யவும். உயர்த்தப்பட்ட படுக்கைகளை பயன்படுத்தவும். தடுப்பு முறையில் பூஞ்சைக்கொல்லிகளை பயன்படுத்தவும். கடும் மழைக்கு முன் அறுவடை செய்யவும்.',
    chilliTip1: '45-60 செமீ இடைவெளியில் நாற்றுகளை நடவு செய்யவும்',
    chilliTip2: 'சிறந்த ஆதரவுக்காக தாவரங்களை கட்டவும்',
    chilliTip3: 'சமநிலை உரங்களை பயன்படுத்தவும், பூக்கும் மற்றும் பழம் காய்க்கும் போது போதுமான நீரை உறுதி செய்யவும்',
    
    // Fertilizer Names
    fertilizerNPK: 'NPK 19:19:19',
    fertilizerUrea: 'யூரியா',
    fertilizerDAP: 'டிஏபி',
    fertilizerPotash: 'பொட்டாஷ்',
    fertilizerCompost: 'உரம்',
    fertilizerOrganicMix: 'கரிம கலவை',
    
    // Dosage Units
    kgPerAcre: 'கிலோ எகர்',
    tonsPerAcre: 'டன் எகர்',
    
    // Fertilizer Remarks (Primary)
    remarkNPK: 'பெரும்பாலான பயிர்களுக்கு ஏற்ற சமநிலை உரம். நடவு செய்யும் போது பயன்படுத்தவும்.',
    remarkUrea: 'அதிக நைட்ரஜன் உள்ளடக்கம். வளர்ச்சி நிலையில் சிறப்பாக பயன்படுத்தலாம்.',
    remarkDAP: 'பாஸ்பரஸ் நிறைந்தது. வேர் வளர்ச்சி மற்றும் பூக்கும் நிலைக்கு சிறந்தது.',
    remarkPotash: 'பழ தரம் மற்றும் நோய் எதிர்ப்புக்கு அவசியம். பழம் காய்க்கும் நிலையில் பயன்படுத்தவும்.',
    remarkCompost: 'கரிம விருப்பம். மண் கட்டமைப்பு மற்றும் ஊட்டச்சத்து தக்கவைப்பை மேம்படுத்துகிறது.',
    remarkOrganicMix: 'முழுமையான கரிம தீர்வு. மண் ஆரோக்கியம் மற்றும் பயிர் தரத்தை மேம்படுத்துகிறது.',
    
    // Alternative Remarks
    altRemarkNPK: 'சமநிலை ஊட்டச்சத்துக்கு நல்ல மாற்று. கரிம பொருட்களுடன் கலக்கலாம்.',
    altRemarkUrea: 'மாற்று நைட்ரஜன் மூலம். சிறந்த திறனுக்காக பிரிக்கப்பட்ட அளவுகளில் பயன்படுத்தவும்.',
    altRemarkDAP: 'மாற்று பாஸ்பரஸ் மூலம். கரிம திருத்தங்களுடன் நன்றாக வேலை செய்கிறது.',
    altRemarkPotash: 'மாற்று பொட்டாசியம் மூலம். பழம் மற்றும் பூ வளர்ச்சிக்கு நல்லது.',
    altRemarkCompost: 'சிறந்த கரிம மாற்று. நீண்ட கால மண் வளத்தை உருவாக்குகிறது.',
    altRemarkOrganicMix: 'நிலையான மாற்று. மண் உயிரியல் பன்முகத்தன்மை மற்றும் ஆரோக்கியத்தை மேம்படுத்துகிறது.',
    
    // Suggestions Translations
    suggestionLowN: 'கால்நடை எருவு அல்லது பச்சை எருவு பயிர்கள் போன்ற நைட்ரஜன் நிறைந்த கரிம பொருட்களைச் சேர்ப்பதைக் கவனியுங்கள்.',
    suggestionLowP: 'பாஸ்பரஸ் அளவு குறைவாக உள்ளது. எலும்பு உணவு அல்லது பாறை பாஸ்பேட் ஆகியவற்றை கரிம மாற்றுகளாகக் கவனியுங்கள்.',
    suggestionLowK: 'பொட்டாசியம் குறைபாடு கண்டறியப்பட்டது. மர சாம்பல் அல்லது வாழைப்பழ தோல்களை கரிம பொட்டாசியம் மூலங்களாகப் பயன்படுத்தலாம்.',
    suggestionAcidic: 'மண் அமிலமானது. pH அளவை படிப்படியாக உயர்த்த சுண்ணாம்பு சேர்ப்பதைக் கவனியுங்கள்.',
    suggestionAlkaline: 'மண் காரமானது. pH குறைக்க கந்தகம் அல்லது கரிம பொருட்களைச் சேர்ப்பதைக் கவனியுங்கள்.',
    suggestionLowMoisture: 'குறைந்த மண் ஈரப்பதம். உரம் பயன்படுத்துவதற்கு முன் போதுமான நீர்ப்பாசனத்தை உறுதி செய்யவும்.',
    suggestionHighTemp: 'அதிக வெப்பநிலை நிலைகள். ஆவியாதல் இழப்பைத் தடுக்க காலை அல்லது மாலையில் உரங்களைப் பயன்படுத்தவும்.',
    suggestionTomato: 'தக்காளிக்கு, பூக்கும் நிலையில் உரத்துடன் பக்க உணவளிப்பதைக் கவனியுங்கள்.',
    suggestionRice: 'நெல்லுக்கு, நைட்ரஜனின் பிரிக்கப்பட்ட பயன்பாடு பரிந்துரைக்கப்படுகிறது - 50% நடவு செய்யும் போது, 25% தில்லிங் நிலையில், 25% பானிக்கிள் தொடக்கத்தில்.',
    suggestionWheat: 'கோதுமைக்கு, விதைக்கும் போது பாஸ்பரஸ் பயன்படுத்தவும் மற்றும் வளர்ச்சி நிலைகளில் நைட்ரஜனை பிரிக்கப்பட்ட அளவுகளில் பயன்படுத்தவும்.',
    suggestionCabbage: 'முட்டைக்கோசுக்கு, இலை வளர்ச்சிக்கு போதுமான நைட்ரஜனை உறுதி செய்யவும். இலை உணவளிப்பதைக் கவனியுங்கள்.',
    suggestionPotato: 'உருளைக்கிழங்குக்கு, அதிக பொட்டாசியம் தேவை. கிழங்கு உருவாக்க நிலையில் பொட்டாஷ் பயன்படுத்தவும்.',
    suggestionCotton: 'பருத்திக்கு, நுண்ணூட்டச்சத்துகளுடன் சமநிலை NPK. துத்தநாகம் மற்றும் போரான் சப்ளிமெண்ட்களைக் கவனியுங்கள்.',
    suggestionDefault: 'பயிர்-குறிப்பிட்ட ஊட்டச்சத்து மேலாண்மை நடைமுறைகளைப் பின்பற்றவும்.',
    consultExpert: 'விவசாய நிபுணரைக் கலந்தாலோசிக்கவும்',
    
    // Language
    language: 'மொழி',
    english: 'English',
    tamil: 'தமிழ்',
    
    // New Features Translations
    soilHealthScore: 'மண் ஆரோக்கிய மதிப்பெண்',
    soilHealthExcellent: 'சிறந்த மண் ஆரோக்கியம்!',
    soilHealthGood: 'நல்லது ஆனால் அதிக கரிமப் பொருட்கள் தேவை.',
    soilHealthFair: 'நடுத்தரம் - மண் மேம்பாடு தேவை.',
    soilHealthPoor: 'மோசமானது - உடனடி மண் சிகிச்சை தேவை.',
    
    pestRiskPredictor: 'பூச்சி ஆபத்து கணிப்பு',
    risk: 'ஆபத்து',
    pestRiskLow: 'குறைந்த',
    pestRiskMedium: 'நடுத்தர',
    pestRiskMediumHigh: 'நடுத்தர-உயர்',
    pestRiskHigh: 'உயர்',
    pestRiskLowMessage: 'குறைந்த பூச்சி ஆபத்து. வழக்கமான கண்காணிப்பு பரிந்துரைக்கப்படுகிறது.',
    pestRiskLowRec: 'வழக்கமான பூச்சி மேலாண்மை நடைமுறைகளைத் தொடரவும்.',
    pestRiskHighMessage: 'பூஞ்சை தொற்றுகளின் அதிக வாய்ப்பு',
    pestRiskHighRec: 'வாரத்திற்கு ஒருமுறை வேப்ப எண்ணெய் பயன்படுத்தவும். சரியான காற்றோட்டத்தை உறுதி செய்யவும்.',
    pestRiskMediumMessage: 'நடுத்தர பூச்சி ஆபத்து கண்டறியப்பட்டது',
    pestRiskMediumRec: 'கண்காணிப்பு அதிர்வெண்ணை அதிகரிக்கவும். கரிம பூச்சி கட்டுப்பாட்டைப் பயன்படுத்தவும்.',
    pestRiskMediumHighMessage: 'நடுத்தர முதல் உயர் பூச்சி தாக்குதல் ஆபத்து',
    pestRiskMediumHighRec: 'தடுப்பு கரிம பூச்சிக்கொல்லிகளைப் பயன்படுத்தவும். தினமும் கண்காணிக்கவும்.',
    pestRiskRiceHigh: 'பிளாஸ்ட் நோய் மற்றும் தண்டு துளைப்பான் அதிக வாய்ப்பு',
    pestRiskRiceRec: 'வேப்ப எண்ணெய் மற்றும் பூஞ்சைக்கொல்லிகளைப் பயன்படுத்தவும். தண்டு துளைப்பானைக் கண்காணிக்கவும். சரியான நீர் மேலாண்மையை உறுதி செய்யவும்.',
    pestRiskRiceMedium: 'நெல் நோய்களின் நடுத்தர ஆபத்து',
    pestRiskRiceRecMedium: 'இலை மடிப்பான் மற்றும் நோய்களைக் கண்காணிக்கவும். தடுப்பு நடவடிக்கைகளைப் பயன்படுத்தவும்.',
    pestRiskVegetableHigh: 'பூஞ்சை தொற்றுகள் மற்றும் பழம் துளைப்பானின் அதிக வாய்ப்பு',
    pestRiskVegetableRec: 'வாரத்திற்கு ஒருமுறை வேப்ப எண்ணெய் பயன்படுத்தவும். சரியான காற்றோட்டத்தை உறுதி செய்யவும். பழம் துளைப்பானைக் கண்காணிக்கவும்.',
    pestRiskVegetableMediumHigh: 'பூச்சி தாக்குதல்களின் நடுத்தர முதல் உயர் ஆபத்து',
    pestRiskVegetableRecMedium: 'தடுப்பு கரிம பூச்சிக்கொல்லிகளைப் பயன்படுத்தவும். அஃபிட்கள் மற்றும் வெள்ளைப்பூச்சியைத் தினமும் கண்காணிக்கவும்.',
    pestRiskCottonHigh: 'பால் புழு மற்றும் வெள்ளைப்பூச்சியின் அதிக ஆபத்து',
    pestRiskCottonRec: 'பால் புழுவை வழக்கமாகக் கண்காணிக்கவும். பிடி பருத்தி அல்லது கரிம பூச்சிக்கொல்லிகளைப் பயன்படுத்தவும்.',
    pestRiskCottonMedium: 'பருத்தியில் நடுத்தர பூச்சி ஆபத்து',
    pestRiskCottonRecMedium: 'கண்காணிப்பு அதிர்வெண்ணை அதிகரிக்கவும். கரிம பூச்சி கட்டுப்பாட்டைப் பயன்படுத்தவும்.',
    
    waterUsageAlert: 'நீர் பயன்பாடு எச்சரிக்கை',
    waterRequirement: 'நீர் தேவை',
    waterVeryHigh: 'மிக அதிகம்',
    waterHigh: 'அதிகம்',
    waterMediumHigh: 'நடுத்தர-அதிகம்',
    waterMedium: 'நடுத்தர',
    waterLowMedium: 'குறைந்த-நடுத்தர',
    waterRice: 'நெல்லுக்கு 1000-2000மிமீ நீர் தேவை. போதுமான நீர்ப்பாசனத்தை உறுதி செய்யவும்.',
    waterSugarcane: 'கரும்புக்கு 1200-2000மிமீ நீர் தேவை. வழக்கமான நீர்ப்பாசனம் அவசியம்.',
    waterCotton: 'பருத்திக்கு 500-800மிமீ நீர் தேவை. மண் ஈரப்பதத்தை வழக்கமாகக் கண்காணிக்கவும்.',
    waterMaize: 'சோளத்திற்கு 500-800மிமீ நீர் தேவை. நடுத்தர நீர்ப்பாசனம் போதுமானது.',
    waterWheat: 'கோதுமைக்கு 400-600மிமீ நீர் தேவை. சரியான நேரத்தில் நீர்ப்பாசனம் முக்கியம்.',
    waterTomato: 'தக்காளிக்கு 600-1000மிமீ நீர் தேவை. நிலையான நீர்ப்பாசனம் முக்கியம்.',
    waterPotato: 'உருளைக்கிழங்குக்கு 500-700மிமீ நீர் தேவை. நீர் தேங்குவதைத் தவிர்க்கவும்.',
    waterOnion: 'வெங்காயத்திற்கு 600-800மிமீ நீர் தேவை. நடுத்தர நீர்ப்பாசனம்.',
    waterCarrot: 'கேரட்டிற்கு 500-700மிமீ நீர் தேவை. வழக்கமான இலகுவான நீர்ப்பாசனம்.',
    waterCucumber: 'வெள்ளரிக்காய்க்கு 600-1000மிமீ நீர் தேவை. அதிக நீர் தேவை.',
    waterWatermelon: 'தர்பூசணிக்கு 500-800மிமீ நீர் தேவை. நிலையான ஈரப்பதம் தேவை.',
    waterBrinjal: 'கத்தரிக்காய்க்கு 600-1000மிமீ நீர் தேவை. வழக்கமான நீர்ப்பாசனம் தேவை.',
    waterChilli: 'மிளகாய்க்கு 500-800மிமீ நீர் தேவை. நடுத்தர நீர்ப்பாசனம் போதுமானது.',
    waterCabbage: 'முட்டைக்கோசுக்கு 600-800மிமீ நீர் தேவை. நிலையான ஈரப்பதம் முக்கியம்.',
    waterCauliflower: 'பூக்கோசுக்கு 600-800மிமீ நீர் தேவை. வழக்கமான நீர்ப்பாசனம் தேவை.',
    waterDefault: 'நடுத்தர நீர் தேவை. மண் ஈரப்பதத்தைக் கண்காணிக்கவும்.',
    
    compostSuggestion: 'உரம் பரிந்துரை',
    compostAlkaline: 'கார உரம்',
    compostAcidic: 'அமில உரம்',
    compostMoistureRetaining: 'ஈரப்பதம் தக்கவைக்கும் உரம்',
    compostDrainage: 'வடிகால் மேம்பாட்டு உரம்',
    compostBalanced: 'சமநிலை உரம்',
    compostRiceAcidic: 'நெல்/கரும்புக்கு: pH அதிகரிக்க சுண்ணாம்பு நிறைந்த உரம் அல்லது மர சாம்பலைச் சேர்க்கவும். கால்சியம் கொண்ட சிதைந்த கரிமப் பொருட்களைப் பயன்படுத்தவும்.',
    compostRice: 'நெல்/கரும்புக்கு: சிறந்த விளைச்சலுக்கு நன்கு சிதைந்த கால்நடை எருவு மற்றும் பச்சை எருவு பயிர்களைப் பயன்படுத்தவும்.',
    compostTomatoAlkaline: 'காய்கறிகளுக்கு: pH குறைக்க பைன் ஊசிகள், காபி தூள் போன்ற அமில உரத்தைச் சேர்க்கவும்.',
    compostTomatoMoisture: 'காய்கறிகளுக்கு: நீர் தக்கவைப்பை மேம்படுத்த தேங்காய் நார், இலை அச்சு போன்ற கரிமப் பொருட்கள் நிறைந்த உரத்தைச் சேர்க்கவும்.',
    compostTomato: 'காய்கறிகளுக்கு: மண் ஆரோக்கியத்தை பராமரிக்க நன்கு சமநிலையான உரத்தை (சமையலறை கழிவுகள், தோட்டக் கழிவுகள்) பயன்படுத்தவும்.',
    compostWheat: 'தானியங்களுக்கு: மண் கட்டமைப்பு மற்றும் ஊட்டச்சத்து கிடைப்பை மேம்படுத்த கால்நடை எருவு மற்றும் உரத்தைப் பயன்படுத்தவும்.',
    compostAlkalineSuggestion: 'pH அதிகரிக்க சுண்ணாம்பு நிறைந்த உரம் அல்லது மர சாம்பலைச் சேர்க்கவும். கால்சியம் கொண்ட சிதைந்த கரிமப் பொருட்களைப் பயன்படுத்தவும்.',
    compostAcidicSuggestion: 'pH குறைக்க பைன் ஊசிகள், காபி தூள் அல்லது பீட் மாஸ் போன்ற அமில உரத்தைச் சேர்க்கவும்.',
    compostMoistureSuggestion: 'நீர் தக்கவைப்பை மேம்படுத்த தேங்காய் நார், இலை அச்சு போன்ற கரிமப் பொருட்கள் நிறைந்த உரத்தைச் சேர்க்கவும்.',
    compostDrainageSuggestion: 'வடிகாலை மேம்படுத்த கரடுமுரடான பொருட்கள் (வைக்கோல், மரத் துண்டுகள்) கொண்ட உரத்தைச் சேர்க்கவும்.',
    compostBalancedSuggestion: 'மண் ஆரோக்கியத்தை பராமரிக்க நன்கு சமநிலையான உரத்தை (சமையலறை கழிவுகள், தோட்டக் கழிவுகள்) பயன்படுத்தவும்.',
    
    cropRotationAdvisor: 'பயிர் சுழற்சி ஆலோசகர்',
    rotationRice: 'நெல்லுக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள் (மூங்கு, உளுந்து), பருப்பு வகைகள், கடுகு',
    rotationWheat: 'கோதுமைக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், எண்ணெய் வித்துக்கள், காய்கறிகள்',
    rotationTomato: 'தக்காளிக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், சோளம், இலை காய்கறிகள்',
    rotationPotato: 'உருளைக்கிழங்குக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், தானியங்கள், கடுகு',
    rotationCotton: 'பருத்திக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், தானியங்கள், எண்ணெய் வித்துக்கள்',
    rotationMaize: 'சோளத்திற்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், கோதுமை, காய்கறிகள்',
    rotationSugarcane: 'கரும்புக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், பருப்பு வகைகள், பச்சை எருவு பயிர்கள்',
    rotationBrinjal: 'கத்தரிக்காய்க்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், இலை காய்கறிகள், வேர் காய்கறிகள்',
    rotationChilli: 'மிளகாய்க்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், வெங்காயம், பூண்டு',
    rotationCabbage: 'முட்டைக்கோசுக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், வேர் காய்கறிகள், சோளம்',
    rotationCauliflower: 'பூக்கோசுக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், இலை காய்கறிகள், பீன்ஸ்',
    rotationCarrot: 'கேரட்டிற்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், இலை காய்கறிகள், வெங்காயம்',
    rotationOnion: 'வெங்காயத்திற்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், இலை காய்கறிகள், வேர் காய்கறிகள்',
    rotationCucumber: 'வெள்ளரிக்காய்க்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், சோளம், இலை காய்கறிகள்',
    rotationWatermelon: 'தர்பூசணிக்குப் பிறகு → நல்ல சுழற்சி பயிர்கள்: பருப்பு வகைகள், இலை காய்கறிகள், வேர் காய்கறிகள்',
    rotationDefault: 'மண் ஆரோக்கியத்தை பராமரிக்க பருப்பு வகைகள் அல்லது வெவ்வேறு பயிர் குடும்பங்களுடன் சுழற்றவும்.',
    
    dailyFarmingTip: 'தினசரி விவசாய உதவிக்குறிப்பு',
    tipRice1: 'நெல் வயல்களில் சரியான நீர் அளவை பராமரிக்கவும் (5-7செமீ)',
    tipRice2: 'சிறந்த திறனுக்காக நைட்ரஜனை பிரிக்கப்பட்ட அளவுகளில் பயன்படுத்தவும்',
    tipRice3: 'போட்டியைத் தடுக்க வழக்கமாக களைகளைக் கட்டுப்படுத்தவும்',
    tipRice4: 'தண்டு துளைப்பான் மற்றும் இலை மடிப்பான் பூச்சிகளைக் கண்காணிக்கவும்',
    tipTomato1: 'சிறந்த ஆதரவு மற்றும் காற்றோட்டத்திற்கு தக்காளி தாவரங்களை கட்டவும்',
    tipTomato2: 'நோய்களைத் தடுக்க இலைகளை நனைக்காமல் அடிப்பகுதியில் நீர்ப்பாசனம் செய்யவும்',
    tipTomato3: 'வழக்கமாக பக்க தளிர்களை (சக்கர்கள்) கத்தரிக்கவும்',
    tipTomato4: 'அதிக பழங்களை ஊக்குவிக்க வழக்கமாக அறுவடை செய்யவும்',
    tipWheat1: 'வேர் வளர்ச்சிக்கு விதைக்கும் போது பாஸ்பரஸைப் பயன்படுத்தவும்',
    tipWheat2: 'களைக்கொல்லிகளுடன் ஆரம்பத்தில் களைகளைக் கட்டுப்படுத்தவும்',
    tipWheat3: 'துரு மற்றும் பவுடரி பூஞ்சை நோய்களைக் கண்காணிக்கவும்',
    tipWheat4: 'தானியங்கள் கடினமாகவும் ஈரப்பதம் 20-25% ஆகவும் இருக்கும்போது அறுவடை செய்யவும்',
    tipSugarcane1: '3-4 பிரிக்கப்பட்ட அளவுகளில் நைட்ரஜனைப் பயன்படுத்தவும்',
    tipSugarcane2: 'நடவு செய்த 45 மற்றும் 90 நாட்களில் மண் சேர்த்தல்',
    tipSugarcane3: 'வளர்ச்சி முழுவதும் போதுமான நீர்ப்பாசனத்தை பராமரிக்கவும்',
    tipSugarcane4: 'பிரிக்ஸ் 18-20% ஆக இருக்கும்போது 10-12 மாதங்களில் அறுவடை செய்யவும்',
    tipCotton1: 'வழக்கமாக பால் புழு மற்றும் வெள்ளைப்பூச்சியைக் கண்காணிக்கவும்',
    tipCotton2: 'சிறந்த விளைச்சலுக்கு நுண்ணூட்டச்சத்துகளை (துத்தநாகம், போரான்) பயன்படுத்தவும்',
    tipCotton3: 'சிறந்த காற்றோட்டத்திற்கு கீழ் கிளைகளை கத்தரிக்கவும்',
    tipCotton4: 'பால்கள் திறந்து பஞ்சு பஞ்சுபோல் இருக்கும்போது அறுவடை செய்யவும்',
    tipDefault1: 'ஆவியாதலைக் குறைக்க காலை அல்லது மாலையில் தாவரங்களுக்கு நீர்ப்பாசனம் செய்யவும்',
    tipDefault2: 'ஈரப்பதத்தை தக்கவைத்து களைகளை அடக்க தாவரங்களைச் சுற்றி மல்ச் செய்யவும்',
    tipDefault3: 'உகந்த ஊட்டச்சத்து கிடைப்பிற்கு வழக்கமாக மண் pH ஐ சோதிக்கவும்',
    tipDefault4: 'மண் கட்டமைப்பை மேம்படுத்த கரிம உரத்தைப் பயன்படுத்தவும்',
    tipDefault5: 'பூச்சி குவிப்பைத் தடுக்க ஆண்டுதோறும் பயிர்களை சுழற்றவும்',
    tipDefault6: 'ஆரம்ப பூச்சி கண்டறிவிற்கு தினமும் தாவரங்களைக் கண்காணிக்கவும்',
    tipDefault7: 'ஆரோக்கியமான வளர்ச்சியை ஊக்குவிக்க வழக்கமாக கத்தரிக்கவும்',
    tipDefault8: 'இயற்கையாக பூச்சிகளைத் தடுக்க துணை நடவு செய்யவும்',
    tipDefault9: 'காற்றோட்டத்திற்கு சரியான இடைவெளியை பராமரிக்கவும்',
    tipDefault10: 'சிறந்த தரத்திற்கு உச்ச முதிர்ச்சியில் அறுவடை செய்யவும்',
    
    plantGrowthStageTips: 'தாவர வளர்ச்சி நிலை உதவிக்குறிப்புகள்',
    seedlingStage: 'நாற்று நிலை',
    vegetativeStage: 'வளர்ச்சி நிலை',
    floweringStage: 'பூக்கும் நிலை',
    harvestStage: 'அறுவடை நிலை',
    stage: 'நிலை',
    
    // Growth Stage Tips - Rice
    riceSeedling1: 'நாற்றங்கிலில் 2-3செமீ நீர் அளவை பராமரிக்கவும்',
    riceSeedling2: 'முளைக்க 25-30°C வெப்பநிலையை பராமரிக்கவும்',
    riceSeedling3: '10 நாட்களுக்குப் பிறகு இலகுவான நைட்ரஜனைப் பயன்படுத்தவும்',
    riceSeedling4: 'பறவைகள் மற்றும் பூச்சிகளிடமிருந்து பாதுகாக்கவும்',
    riceVegetative1: 'வயலில் 5-7செமீ நீர் ஆழத்தை பராமரிக்கவும்',
    riceVegetative2: 'பிரிக்கப்பட்ட அளவுகளில் நைட்ரஜனைப் பயன்படுத்தவும் (நடவு செய்யும் போது 50%, தில்லிங் நிலையில் 25%)',
    riceVegetative3: 'வழக்கமாக களைகளைக் கட்டுப்படுத்தவும்',
    riceVegetative4: 'தண்டு துளைப்பான் மற்றும் இலை மடிப்பானைக் கண்காணிக்கவும்',
    riceFlowering1: 'முக்கியமான நீர் நிலை - 5-10செமீ நீரை பராமரிக்கவும்',
    riceFlowering2: 'பானிக்கிள் தொடக்கத்தில் மீதமுள்ள 25% நைட்ரஜனைப் பயன்படுத்தவும்',
    riceFlowering3: 'பூக்கும் போது நீர் அழுத்தத்தைத் தவிர்க்கவும்',
    riceFlowering4: 'பிளாஸ்ட் நோயைக் கண்காணிக்கவும்',
    riceHarvest1: 'அறுவடைக்கு 10-15 நாட்களுக்கு முன் நீரை வடிகட்டவும்',
    riceHarvest2: '80% தானியங்கள் பொன்னிற மஞ்சளாக மாறும்போது அறுவடை செய்யவும்',
    riceHarvest3: 'ஈரப்பதம் 20-22% ஆக இருக்கும்போது காலையில் அறுவடை செய்யவும்',
    riceHarvest4: 'சேமிப்பிற்கு 14% ஈரப்பதத்திற்கு சரியாக உலர்த்தவும்',
    
    // Growth Stage Tips - Tomato
    tomatoSeedling1: 'நன்கு வடிகால் மண்ணுடன் நாற்றங்கிலில் விதைகளைத் தொடங்கவும்',
    tomatoSeedling2: '20-25°C வெப்பநிலையை பராமரிக்கவும்',
    tomatoSeedling3: '4-5 இலைகள் தோன்றும்போது 25-30 நாட்களுக்குப் பிறகு மாற்றவும்',
    tomatoSeedling4: 'மாற்றுவதற்கு முன் நாற்றுகளை கடினப்படுத்தவும்',
    tomatoVegetative1: 'ஆதரவுக்கு தாவரங்களை கட்டவும்',
    tomatoVegetative2: 'இலை வளர்ச்சிக்கு நைட்ரஜன் நிறைந்த உரத்தைப் பயன்படுத்தவும்',
    tomatoVegetative3: 'வழக்கமாக பக்க தளிர்களை (சக்கர்கள்) கத்தரிக்கவும்',
    tomatoVegetative4: 'இலைகளை நனைக்காமல் அடிப்பகுதியில் நீர்ப்பாசனம் செய்யவும்',
    tomatoFlowering1: 'பூ மற்றும் பழம் அமைப்பிற்கு பாஸ்பரஸைப் பயன்படுத்தவும்',
    tomatoFlowering2: 'அழுத்தத்தைத் தவிர்க்க நிலையான ஈரப்பதத்தை பராமரிக்கவும்',
    tomatoFlowering3: 'குறைந்த ஈரப்பதத்தில் கை மகரந்தச் சேர்க்கை உதவலாம்',
    tomatoFlowering4: 'பூ முனை அழுகலைக் கண்காணிக்கவும்',
    tomatoHarvest1: 'பழங்கள் உறுதியாகவும் முழுமையாக நிறமாகவும் இருக்கும்போது அறுவடை செய்யவும்',
    tomatoHarvest2: 'காலையில் அறுவடை செய்யவும்',
    tomatoHarvest3: 'அதிக பழங்களை ஊக்குவிக்க வழக்கமாக எடுக்கவும்',
    tomatoHarvest4: 'காயங்களைத் தவிர்க்க மென்மையாக கையாளவும்',
    
    // Growth Stage Tips - Wheat
    wheatSeedling1: 'சரியான ஆழத்தில் (5-6செமீ) விதைக்கவும்',
    wheatSeedling2: 'முளைக்க மண் ஈரப்பதத்தை பராமரிக்கவும்',
    wheatSeedling3: 'விதைக்கும் போது பாஸ்பரஸைப் பயன்படுத்தவும்',
    wheatSeedling4: 'பறவைகளிடமிருந்து பாதுகாக்கவும்',
    wheatVegetative1: 'தில்லிங் நிலையில் முதல் நைட்ரஜன் அளவைப் பயன்படுத்தவும்',
    wheatVegetative2: 'களைக்கொல்லிகளுடன் களைகளைக் கட்டுப்படுத்தவும்',
    wheatVegetative3: 'போதுமான இடைவெளியை உறுதி செய்யவும் (20-25செமீ வரிசைகள்)',
    wheatVegetative4: 'துரு மற்றும் பவுடரி பூஞ்சையைக் கண்காணிக்கவும்',
    wheatFlowering1: 'பூட் நிலையில் இரண்டாவது நைட்ரஜன் அளவைப் பயன்படுத்தவும்',
    wheatFlowering2: 'பூக்கும் போது நீர் அழுத்தத்தைத் தவிர்க்கவும்',
    wheatFlowering3: 'அஃபிட்கள் மற்றும் நோய்களைக் கண்காணிக்கவும்',
    wheatFlowering4: 'தானிய நிரப்பத்திற்கு பொட்டாஷுடன் ஆதரவு செய்யவும்',
    wheatHarvest1: 'தானியங்கள் கடினமாகவும் ஈரப்பதம் 20-25% ஆகவும் இருக்கும்போது அறுவடை செய்யவும்',
    wheatHarvest2: 'காலையில் அறுவடை செய்யவும்',
    wheatHarvest3: 'அறுவடைக்குப் பிறகு உடனடியாக தட்டவும்',
    wheatHarvest4: 'சேமிப்பிற்கு 12% ஈரப்பதத்திற்கு உலர்த்தவும்',
    
    // Growth Stage Tips - Sugarcane
    sugarcaneSeedling1: '2-3 மொட்டுகளுடன் செட்டுகளை நடவு செய்யவும்',
    sugarcaneSeedling2: 'முளைக்க மண் ஈரப்பதத்தை பராமரிக்கவும்',
    sugarcaneSeedling3: 'NPK இன் அடிப்படை அளவைப் பயன்படுத்தவும்',
    sugarcaneSeedling4: 'ஆரம்பத்தில் களைகளைக் கட்டுப்படுத்தவும்',
    sugarcaneVegetative1: '3-4 பிரிக்கப்பட்ட அளவுகளில் நைட்ரஜனைப் பயன்படுத்தவும்',
    sugarcaneVegetative2: '45 மற்றும் 90 நாட்களில் மண் சேர்த்தல்',
    sugarcaneVegetative3: 'போதுமான நீர்ப்பாசனத்தை பராமரிக்கவும்',
    sugarcaneVegetative4: 'மேல் துளைப்பான் மற்றும் சிவப்பு அழுகலைக் கண்காணிக்கவும்',
    sugarcaneFlowering1: 'நைட்ரஜனைக் குறைத்து, பொட்டாஷை அதிகரிக்கவும்',
    sugarcaneFlowering2: 'மண் ஈரப்பதத்தை பராமரிக்கவும்',
    sugarcaneFlowering3: 'தேவையில்லை என்றால் பூ தண்டுகளை அகற்றவும்',
    sugarcaneFlowering4: 'பூச்சிகள் மற்றும் நோய்களைக் கண்காணிக்கவும்',
    sugarcaneHarvest1: 'பிரிக்ஸ் 18-20% ஆக இருக்கும்போது 10-12 மாதங்களில் அறுவடை செய்யவும்',
    sugarcaneHarvest2: 'தரை மட்டத்திற்கு அருகில் வெட்டவும்',
    sugarcaneHarvest3: 'காலையில் அறுவடை செய்யவும்',
    sugarcaneHarvest4: 'சிறந்த தரத்திற்கு 24-48 மணிநேரத்திற்குள் நசுக்கவும்',
    
    // Growth Stage Tips - Cotton
    cottonSeedling1: 'சரியான ஆழத்தில் (2-3செமீ) விதைக்கவும்',
    cottonSeedling2: 'மண் வெப்பநிலை 20-25°C ஐ பராமரிக்கவும்',
    cottonSeedling3: 'தோன்றிய பிறகு சரியான இடைவெளிக்கு மெல்லியதாக்கவும்',
    cottonSeedling4: 'ஆரம்ப பருவ பூச்சிகளைக் கட்டுப்படுத்தவும்',
    cottonVegetative1: 'வளர்ச்சி வளர்ச்சிக்கு நைட்ரஜனைப் பயன்படுத்தவும்',
    cottonVegetative2: 'கீழ் கிளைகள் மற்றும் இலைகளை கத்தரிக்கவும்',
    cottonVegetative3: 'பால் புழு மற்றும் வெள்ளைப்பூச்சியைக் கண்காணிக்கவும்',
    cottonVegetative4: 'சரியான தாவர இடைவெளியை பராமரிக்கவும்',
    cottonFlowering1: 'பால் வளர்ச்சிக்கு பாஸ்பரஸ் மற்றும் பொட்டாஷைப் பயன்படுத்தவும்',
    cottonFlowering2: 'முக்கியமான நிலை - நீர் அழுத்தத்தைத் தவிர்க்கவும்',
    cottonFlowering3: 'இளஞ்சிவப்பு பால் புழுவைக் கண்காணிக்கவும்',
    cottonFlowering4: 'நுண்ணூட்டச்சத்துகளுடன் (துத்தநாகம், போரான்) ஆதரவு செய்யவும்',
    cottonHarvest1: 'பால்கள் திறந்து பஞ்சு பஞ்சுபோல் இருக்கும்போது அறுவடை செய்யவும்',
    cottonHarvest2: 'வறண்ட வானிலை நிலைகளில் எடுக்கவும்',
    cottonHarvest3: 'பல எடுப்புகளில் அறுவடை செய்யவும்',
    cottonHarvest4: 'வறண்ட, சுத்தமான இடத்தில் சேமிக்கவும்',
    
    // Default Growth Stage Tips
    defaultSeedling1: 'நிலையான ஈரப்பதத்தை பராமரிக்கவும் - மிகவும் ஈரமாகவோ அல்லது மிகவும் வறண்டதாகவோ இல்லை',
    defaultSeedling2: 'மென்மையான ஒளியை வழங்கவும் - நேரடி கடுமையான சூரிய ஒளியைத் தவிர்க்கவும்',
    defaultSeedling3: '20-25°C இடையே வெப்பநிலையை நிலையாக பராமரிக்கவும்',
    defaultSeedling4: 'தேவைப்பட்டால் நீர்த்த உரத்தைப் பயன்படுத்தவும்',
    defaultVegetative1: 'இலை வளர்ச்சிக்கு நைட்ரஜனை அதிகரிக்கவும்',
    defaultVegetative2: 'காற்றோட்டத்திற்கு போதுமான இடைவெளியை உறுதி செய்யவும்',
    defaultVegetative3: 'ஆழமாக ஆனால் குறைவாக நீர்ப்பாசனம் செய்யவும்',
    defaultVegetative4: 'ஆரம்ப பூச்சி அறிகுறிகளைக் கண்காணிக்கவும்',
    defaultFlowering1: 'பூ வளர்ச்சிக்கு பாஸ்பரஸை அதிகரிக்கவும்',
    defaultFlowering2: 'நிலையான நீர்ப்பாசன அட்டவணையை பராமரிக்கவும்',
    defaultFlowering3: 'பூ சேதத்தைத் தடுக்க மேலே நீர்ப்பாசனத்தைத் தவிர்க்கவும்',
    defaultFlowering4: 'தேவைப்பட்டால் தாவரங்களை ஆதரிக்கவும் (கட்டுதல்)',
    defaultHarvest1: 'அறுவடைக்கு முன் நீர்ப்பாசனத்தைக் குறைக்கவும்',
    defaultHarvest2: 'சிறந்த தரத்திற்கு காலையில் அறுவடை செய்யவும்',
    defaultHarvest3: 'பயிருக்கு குறிப்பிட்ட முதிர்ச்சி குறிகாட்டிகளைச் சரிபார்க்கவும்',
    defaultHarvest4: 'காயங்களைத் தவிர்க்க மென்மையாக கையாளவும்',
    
    aiIrrigationAlert: 'AI நீர்ப்பாசன எச்சரிக்கை',
    irrigationAlertRain: '2 மணி நேரத்தில் மழை எதிர்பார்க்கப்படுகிறது — இப்போது நீர்ப்பாசனம் செய்ய வேண்டாம்.',
    irrigationAlertSafe: 'மழை எதிர்பார்க்கப்படவில்லை. நீர்ப்பாசனம் செய்ய பாதுகாப்பானது.',
    in2Hours: '2 மணி நேரம்',
    next24Hours: 'அடுத்த 24 மணி நேரம்',
    
    estimatedCost: '💰 மதிப்பிடப்பட்ட செலவு',
    perKg: 'கிலோவுக்கு',
    approx: 'தோராயமாக',
    for: 'க்கு',
    hectares: 'ஹெக்டேர்',
    
    // YouTube Videos
    learningVideos: '📺 கற்றல் வீடியோக்கள்',
    videoTutorials: 'வீடியோ பயிற்சிகள்',
    learnHowToFarm: 'விவசாயம் செய்வது எப்படி என்று கற்றுக்கொள்ளுங்கள்',
    watchOnYouTube: 'YouTube இல் பார்க்கவும்',
    videoCategory: 'வகை',
    videoDuration: 'கால அளவு',
    noVideosAvailable: 'இந்த பயிருக்கு வீடியோக்கள் கிடைக்கவில்லை',
    loadingVideos: 'வீடியோ பரிந்துரைகளை ஏற்றுகிறது...',
    videoDescription: 'விளக்கம்',
    farmingTutorials: 'விவசாய பயிற்சிகள்',
    completeGuide: 'முழுமையான வழிகாட்டி',
    pestControl: 'பூச்சி கட்டுப்பாடு',
    diseaseManagement: 'நோய் மேலாண்மை',
    organicFarming: 'கரிம விவசாயம்',
    cultivationTechnique: 'சாகுபடி நுட்பம்',
    harvesting: 'அறுவடை',
    irrigation: 'நீர்ப்பாசனம்',
    advancedMethods: 'மேம்பட்ட முறைகள்',
    postHarvest: 'அறுவடைக்குப் பிறகு'
  }
};

